// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SF.Flat.Game
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ChatChannelPlayerJoinedS2CEvt : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_7(); }
  public static ChatChannelPlayerJoinedS2CEvt GetRootAsChatChannelPlayerJoinedS2CEvt(ByteBuffer _bb) { return GetRootAsChatChannelPlayerJoinedS2CEvt(_bb, new ChatChannelPlayerJoinedS2CEvt()); }
  public static ChatChannelPlayerJoinedS2CEvt GetRootAsChatChannelPlayerJoinedS2CEvt(ByteBuffer _bb, ChatChannelPlayerJoinedS2CEvt obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ChatChannelPlayerJoinedS2CEvt __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public SF.Flat.EntityUID? ChatUid { get { int o = __p.__offset(4); return o != 0 ? (SF.Flat.EntityUID?)(new SF.Flat.EntityUID()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public SF.Flat.PlayerInformation? JoinedPlayer { get { int o = __p.__offset(6); return o != 0 ? (SF.Flat.PlayerInformation?)(new SF.Flat.PlayerInformation()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static void StartChatChannelPlayerJoinedS2CEvt(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddChatUid(FlatBufferBuilder builder, Offset<SF.Flat.EntityUID> chatUidOffset) { builder.AddStruct(0, chatUidOffset.Value, 0); }
  public static void AddJoinedPlayer(FlatBufferBuilder builder, Offset<SF.Flat.PlayerInformation> joinedPlayerOffset) { builder.AddOffset(1, joinedPlayerOffset.Value, 0); }
  public static Offset<SF.Flat.Game.ChatChannelPlayerJoinedS2CEvt> EndChatChannelPlayerJoinedS2CEvt(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SF.Flat.Game.ChatChannelPlayerJoinedS2CEvt>(o);
  }
}


static public class ChatChannelPlayerJoinedS2CEvtVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*ChatUid*/, 4 /*SF.Flat.EntityUID*/, 4, false)
      && verifier.VerifyTable(tablePos, 6 /*JoinedPlayer*/, SF.Flat.PlayerInformationVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
