// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SF.Flat.Game
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct FindPlayerByCharacterNameCmd : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static FindPlayerByCharacterNameCmd GetRootAsFindPlayerByCharacterNameCmd(ByteBuffer _bb) { return GetRootAsFindPlayerByCharacterNameCmd(_bb, new FindPlayerByCharacterNameCmd()); }
  public static FindPlayerByCharacterNameCmd GetRootAsFindPlayerByCharacterNameCmd(ByteBuffer _bb, FindPlayerByCharacterNameCmd obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FindPlayerByCharacterNameCmd __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string CharacterName { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetCharacterNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetCharacterNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetCharacterNameArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<SF.Flat.Game.FindPlayerByCharacterNameCmd> CreateFindPlayerByCharacterNameCmd(FlatBufferBuilder builder,
      StringOffset character_nameOffset = default(StringOffset)) {
    builder.StartTable(1);
    FindPlayerByCharacterNameCmd.AddCharacterName(builder, character_nameOffset);
    return FindPlayerByCharacterNameCmd.EndFindPlayerByCharacterNameCmd(builder);
  }

  public static void StartFindPlayerByCharacterNameCmd(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddCharacterName(FlatBufferBuilder builder, StringOffset characterNameOffset) { builder.AddOffset(0, characterNameOffset.Value, 0); }
  public static Offset<SF.Flat.Game.FindPlayerByCharacterNameCmd> EndFindPlayerByCharacterNameCmd(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SF.Flat.Game.FindPlayerByCharacterNameCmd>(o);
  }
}


static public class FindPlayerByCharacterNameCmdVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*CharacterName*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
