// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SF.Flat.Game
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct GetMyUGCGamesRes : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_7(); }
  public static GetMyUGCGamesRes GetRootAsGetMyUGCGamesRes(ByteBuffer _bb) { return GetRootAsGetMyUGCGamesRes(_bb, new GetMyUGCGamesRes()); }
  public static GetMyUGCGamesRes GetRootAsGetMyUGCGamesRes(ByteBuffer _bb, GetMyUGCGamesRes obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public GetMyUGCGamesRes __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public SF.Flat.UGCContentInfo? ContentInfos(int j) { int o = __p.__offset(4); return o != 0 ? (SF.Flat.UGCContentInfo?)(new SF.Flat.UGCContentInfo()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ContentInfosLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<SF.Flat.Game.GetMyUGCGamesRes> CreateGetMyUGCGamesRes(FlatBufferBuilder builder,
      VectorOffset content_infosOffset = default(VectorOffset)) {
    builder.StartTable(1);
    GetMyUGCGamesRes.AddContentInfos(builder, content_infosOffset);
    return GetMyUGCGamesRes.EndGetMyUGCGamesRes(builder);
  }

  public static void StartGetMyUGCGamesRes(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddContentInfos(FlatBufferBuilder builder, VectorOffset contentInfosOffset) { builder.AddOffset(0, contentInfosOffset.Value, 0); }
  public static VectorOffset CreateContentInfosVector(FlatBufferBuilder builder, Offset<SF.Flat.UGCContentInfo>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateContentInfosVectorBlock(FlatBufferBuilder builder, Offset<SF.Flat.UGCContentInfo>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateContentInfosVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<SF.Flat.UGCContentInfo>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateContentInfosVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<SF.Flat.UGCContentInfo>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartContentInfosVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<SF.Flat.Game.GetMyUGCGamesRes> EndGetMyUGCGamesRes(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SF.Flat.Game.GetMyUGCGamesRes>(o);
  }
}


static public class GetMyUGCGamesResVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfTables(tablePos, 4 /*ContentInfos*/, SF.Flat.UGCContentInfoVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
