// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SF.Flat.Game
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct JoinGameServerCmd : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static JoinGameServerCmd GetRootAsJoinGameServerCmd(ByteBuffer _bb) { return GetRootAsJoinGameServerCmd(_bb, new JoinGameServerCmd()); }
  public static JoinGameServerCmd GetRootAsJoinGameServerCmd(ByteBuffer _bb, JoinGameServerCmd obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public JoinGameServerCmd __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong AccId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public ulong Ticket { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public ulong LoginEntityUid { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }

  public static Offset<SF.Flat.Game.JoinGameServerCmd> CreateJoinGameServerCmd(FlatBufferBuilder builder,
      ulong acc_id = 0,
      ulong ticket = 0,
      ulong login_entity_uid = 0) {
    builder.StartTable(3);
    JoinGameServerCmd.AddLoginEntityUid(builder, login_entity_uid);
    JoinGameServerCmd.AddTicket(builder, ticket);
    JoinGameServerCmd.AddAccId(builder, acc_id);
    return JoinGameServerCmd.EndJoinGameServerCmd(builder);
  }

  public static void StartJoinGameServerCmd(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddAccId(FlatBufferBuilder builder, ulong accId) { builder.AddUlong(0, accId, 0); }
  public static void AddTicket(FlatBufferBuilder builder, ulong ticket) { builder.AddUlong(1, ticket, 0); }
  public static void AddLoginEntityUid(FlatBufferBuilder builder, ulong loginEntityUid) { builder.AddUlong(2, loginEntityUid, 0); }
  public static Offset<SF.Flat.Game.JoinGameServerCmd> EndJoinGameServerCmd(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SF.Flat.Game.JoinGameServerCmd>(o);
  }
}


static public class JoinGameServerCmdVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*AccId*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*Ticket*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 8 /*LoginEntityUid*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
