// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SF.Flat.Game
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct LeavePartyCmd : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_7(); }
  public static LeavePartyCmd GetRootAsLeavePartyCmd(ByteBuffer _bb) { return GetRootAsLeavePartyCmd(_bb, new LeavePartyCmd()); }
  public static LeavePartyCmd GetRootAsLeavePartyCmd(ByteBuffer _bb, LeavePartyCmd obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public LeavePartyCmd __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong PartyUid { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public ulong PlayerId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }

  public static Offset<SF.Flat.Game.LeavePartyCmd> CreateLeavePartyCmd(FlatBufferBuilder builder,
      ulong party_uid = 0,
      ulong player_id = 0) {
    builder.StartTable(2);
    LeavePartyCmd.AddPlayerId(builder, player_id);
    LeavePartyCmd.AddPartyUid(builder, party_uid);
    return LeavePartyCmd.EndLeavePartyCmd(builder);
  }

  public static void StartLeavePartyCmd(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddPartyUid(FlatBufferBuilder builder, ulong partyUid) { builder.AddUlong(0, partyUid, 0); }
  public static void AddPlayerId(FlatBufferBuilder builder, ulong playerId) { builder.AddUlong(1, playerId, 0); }
  public static Offset<SF.Flat.Game.LeavePartyCmd> EndLeavePartyCmd(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SF.Flat.Game.LeavePartyCmd>(o);
  }
}


static public class LeavePartyCmdVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*PartyUid*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*PlayerId*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
