// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SF.Flat.Game
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct PartyPlayerKickedS2CEvt : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static PartyPlayerKickedS2CEvt GetRootAsPartyPlayerKickedS2CEvt(ByteBuffer _bb) { return GetRootAsPartyPlayerKickedS2CEvt(_bb, new PartyPlayerKickedS2CEvt()); }
  public static PartyPlayerKickedS2CEvt GetRootAsPartyPlayerKickedS2CEvt(ByteBuffer _bb, PartyPlayerKickedS2CEvt obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PartyPlayerKickedS2CEvt __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong PartyUid { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public ulong KickedPlayerId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }

  public static Offset<SF.Flat.Game.PartyPlayerKickedS2CEvt> CreatePartyPlayerKickedS2CEvt(FlatBufferBuilder builder,
      ulong party_uid = 0,
      ulong kicked_player_id = 0) {
    builder.StartTable(2);
    PartyPlayerKickedS2CEvt.AddKickedPlayerId(builder, kicked_player_id);
    PartyPlayerKickedS2CEvt.AddPartyUid(builder, party_uid);
    return PartyPlayerKickedS2CEvt.EndPartyPlayerKickedS2CEvt(builder);
  }

  public static void StartPartyPlayerKickedS2CEvt(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddPartyUid(FlatBufferBuilder builder, ulong partyUid) { builder.AddUlong(0, partyUid, 0); }
  public static void AddKickedPlayerId(FlatBufferBuilder builder, ulong kickedPlayerId) { builder.AddUlong(1, kickedPlayerId, 0); }
  public static Offset<SF.Flat.Game.PartyPlayerKickedS2CEvt> EndPartyPlayerKickedS2CEvt(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SF.Flat.Game.PartyPlayerKickedS2CEvt>(o);
  }
}


static public class PartyPlayerKickedS2CEvtVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*PartyUid*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*KickedPlayerId*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
