// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SF.Flat.Game
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct PartyKickPlayerCmd : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static PartyKickPlayerCmd GetRootAsPartyKickPlayerCmd(ByteBuffer _bb) { return GetRootAsPartyKickPlayerCmd(_bb, new PartyKickPlayerCmd()); }
  public static PartyKickPlayerCmd GetRootAsPartyKickPlayerCmd(ByteBuffer _bb, PartyKickPlayerCmd obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PartyKickPlayerCmd __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong PartyUid { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public ulong PlayerId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public ulong PlayerToKick { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }

  public static Offset<SF.Flat.Game.PartyKickPlayerCmd> CreatePartyKickPlayerCmd(FlatBufferBuilder builder,
      ulong party_uid = 0,
      ulong player_id = 0,
      ulong player_to_kick = 0) {
    builder.StartTable(3);
    PartyKickPlayerCmd.AddPlayerToKick(builder, player_to_kick);
    PartyKickPlayerCmd.AddPlayerId(builder, player_id);
    PartyKickPlayerCmd.AddPartyUid(builder, party_uid);
    return PartyKickPlayerCmd.EndPartyKickPlayerCmd(builder);
  }

  public static void StartPartyKickPlayerCmd(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddPartyUid(FlatBufferBuilder builder, ulong partyUid) { builder.AddUlong(0, partyUid, 0); }
  public static void AddPlayerId(FlatBufferBuilder builder, ulong playerId) { builder.AddUlong(1, playerId, 0); }
  public static void AddPlayerToKick(FlatBufferBuilder builder, ulong playerToKick) { builder.AddUlong(2, playerToKick, 0); }
  public static Offset<SF.Flat.Game.PartyKickPlayerCmd> EndPartyKickPlayerCmd(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SF.Flat.Game.PartyKickPlayerCmd>(o);
  }
}


static public class PartyKickPlayerCmdVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*PartyUid*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*PlayerId*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 8 /*PlayerToKick*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
