// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SF.Flat.Game
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct RequestUGCGameInstanceCmd : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_7(); }
  public static RequestUGCGameInstanceCmd GetRootAsRequestUGCGameInstanceCmd(ByteBuffer _bb) { return GetRootAsRequestUGCGameInstanceCmd(_bb, new RequestUGCGameInstanceCmd()); }
  public static RequestUGCGameInstanceCmd GetRootAsRequestUGCGameInstanceCmd(ByteBuffer _bb, RequestUGCGameInstanceCmd obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public RequestUGCGameInstanceCmd __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public SF.Flat.Guid? UgccontentId { get { int o = __p.__offset(4); return o != 0 ? (SF.Flat.Guid?)(new SF.Flat.Guid()).__assign(o + __p.bb_pos, __p.bb) : null; } }

  public static void StartRequestUGCGameInstanceCmd(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddUgccontentId(FlatBufferBuilder builder, Offset<SF.Flat.Guid> ugccontentIdOffset) { builder.AddStruct(0, ugccontentIdOffset.Value, 0); }
  public static Offset<SF.Flat.Game.RequestUGCGameInstanceCmd> EndRequestUGCGameInstanceCmd(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SF.Flat.Game.RequestUGCGameInstanceCmd>(o);
  }
}


static public class RequestUGCGameInstanceCmdVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*UgccontentId*/, 16 /*SF.Flat.Guid*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
