// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SF.Flat.Game
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SetNickNameRes : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static SetNickNameRes GetRootAsSetNickNameRes(ByteBuffer _bb) { return GetRootAsSetNickNameRes(_bb, new SetNickNameRes()); }
  public static SetNickNameRes GetRootAsSetNickNameRes(ByteBuffer _bb, SetNickNameRes obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SetNickNameRes __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Result { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public ulong TotalGem { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public ulong TotalGameMoney { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }

  public static Offset<SF.Flat.Game.SetNickNameRes> CreateSetNickNameRes(FlatBufferBuilder builder,
      uint result = 0,
      ulong total_gem = 0,
      ulong total_game_money = 0) {
    builder.StartTable(3);
    SetNickNameRes.AddTotalGameMoney(builder, total_game_money);
    SetNickNameRes.AddTotalGem(builder, total_gem);
    SetNickNameRes.AddResult(builder, result);
    return SetNickNameRes.EndSetNickNameRes(builder);
  }

  public static void StartSetNickNameRes(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddResult(FlatBufferBuilder builder, uint result) { builder.AddUint(0, result, 0); }
  public static void AddTotalGem(FlatBufferBuilder builder, ulong totalGem) { builder.AddUlong(1, totalGem, 0); }
  public static void AddTotalGameMoney(FlatBufferBuilder builder, ulong totalGameMoney) { builder.AddUlong(2, totalGameMoney, 0); }
  public static Offset<SF.Flat.Game.SetNickNameRes> EndSetNickNameRes(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SF.Flat.Game.SetNickNameRes>(o);
  }
}


static public class SetNickNameResVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Result*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*TotalGem*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 8 /*TotalGameMoney*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
