// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SF.Flat.Game
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct UnregisterGCMRes : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_7(); }
  public static UnregisterGCMRes GetRootAsUnregisterGCMRes(ByteBuffer _bb) { return GetRootAsUnregisterGCMRes(_bb, new UnregisterGCMRes()); }
  public static UnregisterGCMRes GetRootAsUnregisterGCMRes(ByteBuffer _bb, UnregisterGCMRes obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public UnregisterGCMRes __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartUnregisterGCMRes(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<SF.Flat.Game.UnregisterGCMRes> EndUnregisterGCMRes(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SF.Flat.Game.UnregisterGCMRes>(o);
  }
}


static public class UnregisterGCMResVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
