// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SF.Flat.Game
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct UnregisterGCMCmd : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_7(); }
  public static UnregisterGCMCmd GetRootAsUnregisterGCMCmd(ByteBuffer _bb) { return GetRootAsUnregisterGCMCmd(_bb, new UnregisterGCMCmd()); }
  public static UnregisterGCMCmd GetRootAsUnregisterGCMCmd(ByteBuffer _bb, UnregisterGCMCmd obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public UnregisterGCMCmd __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string GcmregisteredId { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetGcmregisteredIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetGcmregisteredIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetGcmregisteredIdArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<SF.Flat.Game.UnregisterGCMCmd> CreateUnregisterGCMCmd(FlatBufferBuilder builder,
      StringOffset gcmregistered_idOffset = default(StringOffset)) {
    builder.StartTable(1);
    UnregisterGCMCmd.AddGcmregisteredId(builder, gcmregistered_idOffset);
    return UnregisterGCMCmd.EndUnregisterGCMCmd(builder);
  }

  public static void StartUnregisterGCMCmd(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddGcmregisteredId(FlatBufferBuilder builder, StringOffset gcmregisteredIdOffset) { builder.AddOffset(0, gcmregisteredIdOffset.Value, 0); }
  public static Offset<SF.Flat.Game.UnregisterGCMCmd> EndUnregisterGCMCmd(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SF.Flat.Game.UnregisterGCMCmd>(o);
  }
}


static public class UnregisterGCMCmdVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*GcmregisteredId*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
