// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SF.Flat
{

public enum GameStateID : sbyte
{
  None = 0,
  Red = 1,
  Green = 2,
  Blue = 3,
};


}
