// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SF.Flat
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct GameInstanceUID : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public GameInstanceUID __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Uid { get { return __p.bb.GetUint(__p.bb_pos + 0); } }

  public static Offset<SF.Flat.GameInstanceUID> CreateGameInstanceUID(FlatBufferBuilder builder, uint Uid) {
    builder.Prep(4, 4);
    builder.PutUint(Uid);
    return new Offset<SF.Flat.GameInstanceUID>(builder.Offset);
  }
}


}
