// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SF.Flat
{

public enum GameWinner : sbyte
{
  None = 0,
  Werewolf = 1,
  Villager = 2,
  WereHamster = 3,
};


}
