// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SF.Flat
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct UGCContentInfo : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_7(); }
  public static UGCContentInfo GetRootAsUGCContentInfo(ByteBuffer _bb) { return GetRootAsUGCContentInfo(_bb, new UGCContentInfo()); }
  public static UGCContentInfo GetRootAsUGCContentInfo(ByteBuffer _bb, UGCContentInfo obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public UGCContentInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public SF.Flat.Guid? UgcContentId { get { int o = __p.__offset(4); return o != 0 ? (SF.Flat.Guid?)(new SF.Flat.Guid()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public SF.Flat.AttributeString? Attributes(int j) { int o = __p.__offset(6); return o != 0 ? (SF.Flat.AttributeString?)(new SF.Flat.AttributeString()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int AttributesLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static void StartUGCContentInfo(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddUgcContentId(FlatBufferBuilder builder, Offset<SF.Flat.Guid> ugcContentIdOffset) { builder.AddStruct(0, ugcContentIdOffset.Value, 0); }
  public static void AddAttributes(FlatBufferBuilder builder, VectorOffset attributesOffset) { builder.AddOffset(1, attributesOffset.Value, 0); }
  public static VectorOffset CreateAttributesVector(FlatBufferBuilder builder, Offset<SF.Flat.AttributeString>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateAttributesVectorBlock(FlatBufferBuilder builder, Offset<SF.Flat.AttributeString>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateAttributesVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<SF.Flat.AttributeString>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateAttributesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<SF.Flat.AttributeString>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartAttributesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<SF.Flat.UGCContentInfo> EndUGCContentInfo(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SF.Flat.UGCContentInfo>(o);
  }
}


static public class UGCContentInfoVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*UgcContentId*/, 16 /*SF.Flat.Guid*/, 8, false)
      && verifier.VerifyVectorOfTables(tablePos, 6 /*Attributes*/, SF.Flat.AttributeStringVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
