// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SF.Flat
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct UGCGameInfo : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_7(); }
  public static UGCGameInfo GetRootAsUGCGameInfo(ByteBuffer _bb) { return GetRootAsUGCGameInfo(_bb, new UGCGameInfo()); }
  public static UGCGameInfo GetRootAsUGCGameInfo(ByteBuffer _bb, UGCGameInfo obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public UGCGameInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public SF.Flat.Guid? UgcContentId { get { int o = __p.__offset(4); return o != 0 ? (SF.Flat.Guid?)(new SF.Flat.Guid()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public uint TableId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public string Name { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(8); }

  public static void StartUGCGameInfo(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddUgcContentId(FlatBufferBuilder builder, Offset<SF.Flat.Guid> ugcContentIdOffset) { builder.AddStruct(0, ugcContentIdOffset.Value, 0); }
  public static void AddTableId(FlatBufferBuilder builder, uint tableId) { builder.AddUint(1, tableId, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(2, nameOffset.Value, 0); }
  public static Offset<SF.Flat.UGCGameInfo> EndUGCGameInfo(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 8);  // name
    return new Offset<SF.Flat.UGCGameInfo>(o);
  }
}


static public class UGCGameInfoVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*UgcContentId*/, 16 /*SF.Flat.Guid*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*TableId*/, 4 /*uint*/, 4, false)
      && verifier.VerifyString(tablePos, 8 /*Name*/, true)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
