

set CMAKE_SYSTEM_NAME=Windows
set PROCESS_ARCHITECTUR=x64
set LIB_PATH=2.13

call ..\..\FindVC.cmd

if not exist %CMAKE_SYSTEM_NAME% mkdir %CMAKE_SYSTEM_NAME%
if not exist %CMAKE_SYSTEM_NAME%\Debug mkdir %CMAKE_SYSTEM_NAME%\Debug
if not exist %CMAKE_SYSTEM_NAME%\RelWithDebInfo mkdir %CMAKE_SYSTEM_NAME%\RelWithDebInfo

cd %CMAKE_SYSTEM_NAME%


set CONFIGURATION=Debug
cd %CONFIGURATION%
cmake ../../%LIB_PATH% -G %VCCMAKEGENERATOR% -A %PROCESS_ARCHITECTUR%  ^
	-DCMAKE_INSTALL_PREFIX=../../../../%CMAKE_SYSTEM_NAME%/%CONFIGURATION%  -DCMAKE_SYSTEM_NAME=%CMAKE_SYSTEM_NAME% ^
	-DJANSSON_BUILD_DOCS=OFF -DJANSSON_EXAMPLES=OFF -DJANSSON_WITHOUT_TESTS=1
cd ..

set CONFIGURATION=RelWithDebInfo
cd %CONFIGURATION%
cmake ../../%LIB_PATH% -G %VCCMAKEGENERATOR% -A %PROCESS_ARCHITECTUR%  ^
	-DCMAKE_INSTALL_PREFIX=../../../../%CMAKE_SYSTEM_NAME%/%CONFIGURATION%  -DCMAKE_SYSTEM_NAME=%CMAKE_SYSTEM_NAME% ^
	-DJANSSON_BUILD_DOCS=OFF -DJANSSON_EXAMPLES=OFF -DJANSSON_WITHOUT_TESTS=1
cd ..
cd ..
