

set CMAKE_SYSTEM_NAME=Windows
set PROCESS_ARCHITECTUR=x64
set SRC_PATH=../../../src/jansson/2.13
set INTERMEDIATE_DIR=..\..\%CMAKE_SYSTEM_NAME%\jansson

call ..\..\FindVC.cmd

if not exist %INTERMEDIATE_DIR% mkdir %INTERMEDIATE_DIR%
if not exist %INTERMEDIATE_DIR%\Debug mkdir %INTERMEDIATE_DIR%\Debug
if not exist %INTERMEDIATE_DIR%\RelWithDebInfo mkdir %INTERMEDIATE_DIR%\RelWithDebInfo

cd %INTERMEDIATE_DIR%


set CONFIGURATION=Debug
cd %CONFIGURATION%
cmake %SRC_PATH% -G %VCCMAKEGENERATOR% -A %PROCESS_ARCHITECTUR%  ^
	-DCMAKE_INSTALL_PREFIX=../../%CONFIGURATION%  -DCMAKE_SYSTEM_NAME=%CMAKE_SYSTEM_NAME% ^
	-DJANSSON_BUILD_DOCS=OFF -DJANSSON_EXAMPLES=OFF -DJANSSON_WITHOUT_TESTS=1
cd ..

set CONFIGURATION=RelWithDebInfo
cd %CONFIGURATION%
cmake %SRC_PATH% -G %VCCMAKEGENERATOR% -A %PROCESS_ARCHITECTUR%  ^
	-DCMAKE_INSTALL_PREFIX=../../%CONFIGURATION%  -DCMAKE_SYSTEM_NAME=%CMAKE_SYSTEM_NAME% ^
	-DJANSSON_BUILD_DOCS=OFF -DJANSSON_EXAMPLES=OFF -DJANSSON_WITHOUT_TESTS=1

cd %~dp0
