// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SF.Flat.PlayInstance
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ActorMovementS2CEvt : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_7(); }
  public static ActorMovementS2CEvt GetRootAsActorMovementS2CEvt(ByteBuffer _bb) { return GetRootAsActorMovementS2CEvt(_bb, new ActorMovementS2CEvt()); }
  public static ActorMovementS2CEvt GetRootAsActorMovementS2CEvt(ByteBuffer _bb, ActorMovementS2CEvt obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ActorMovementS2CEvt __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public SF.Flat.GameInstanceUID? PlayInstanceUid { get { int o = __p.__offset(4); return o != 0 ? (SF.Flat.GameInstanceUID?)(new SF.Flat.GameInstanceUID()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public SF.Flat.ActorMovement? Movement { get { int o = __p.__offset(6); return o != 0 ? (SF.Flat.ActorMovement?)(new SF.Flat.ActorMovement()).__assign(o + __p.bb_pos, __p.bb) : null; } }

  public static void StartActorMovementS2CEvt(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddPlayInstanceUid(FlatBufferBuilder builder, Offset<SF.Flat.GameInstanceUID> playInstanceUidOffset) { builder.AddStruct(0, playInstanceUidOffset.Value, 0); }
  public static void AddMovement(FlatBufferBuilder builder, Offset<SF.Flat.ActorMovement> movementOffset) { builder.AddStruct(1, movementOffset.Value, 0); }
  public static Offset<SF.Flat.PlayInstance.ActorMovementS2CEvt> EndActorMovementS2CEvt(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SF.Flat.PlayInstance.ActorMovementS2CEvt>(o);
  }
}


static public class ActorMovementS2CEvtVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*PlayInstanceUid*/, 4 /*SF.Flat.GameInstanceUID*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*Movement*/, 48 /*SF.Flat.ActorMovement*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
