// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SF.Flat.PlayInstance
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CharacterPublicDataChangedS2CEvt : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_7(); }
  public static CharacterPublicDataChangedS2CEvt GetRootAsCharacterPublicDataChangedS2CEvt(ByteBuffer _bb) { return GetRootAsCharacterPublicDataChangedS2CEvt(_bb, new CharacterPublicDataChangedS2CEvt()); }
  public static CharacterPublicDataChangedS2CEvt GetRootAsCharacterPublicDataChangedS2CEvt(ByteBuffer _bb, CharacterPublicDataChangedS2CEvt obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CharacterPublicDataChangedS2CEvt __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong PlayInstanceUid { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public ulong PlayerId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public byte PublicData(int j) { int o = __p.__offset(8); return o != 0 ? __p.bb.Get(__p.__vector(o) + j * 1) : (byte)0; }
  public int PublicDataLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<byte> GetPublicDataBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetPublicDataBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetPublicDataArray() { return __p.__vector_as_array<byte>(8); }

  public static Offset<SF.Flat.PlayInstance.CharacterPublicDataChangedS2CEvt> CreateCharacterPublicDataChangedS2CEvt(FlatBufferBuilder builder,
      ulong play_instance_uid = 0,
      ulong player_id = 0,
      VectorOffset public_dataOffset = default(VectorOffset)) {
    builder.StartTable(3);
    CharacterPublicDataChangedS2CEvt.AddPlayerId(builder, player_id);
    CharacterPublicDataChangedS2CEvt.AddPlayInstanceUid(builder, play_instance_uid);
    CharacterPublicDataChangedS2CEvt.AddPublicData(builder, public_dataOffset);
    return CharacterPublicDataChangedS2CEvt.EndCharacterPublicDataChangedS2CEvt(builder);
  }

  public static void StartCharacterPublicDataChangedS2CEvt(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddPlayInstanceUid(FlatBufferBuilder builder, ulong playInstanceUid) { builder.AddUlong(0, playInstanceUid, 0); }
  public static void AddPlayerId(FlatBufferBuilder builder, ulong playerId) { builder.AddUlong(1, playerId, 0); }
  public static void AddPublicData(FlatBufferBuilder builder, VectorOffset publicDataOffset) { builder.AddOffset(2, publicDataOffset.Value, 0); }
  public static VectorOffset CreatePublicDataVector(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddByte(data[i]); return builder.EndVector(); }
  public static VectorOffset CreatePublicDataVectorBlock(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreatePublicDataVectorBlock(FlatBufferBuilder builder, ArraySegment<byte> data) { builder.StartVector(1, data.Count, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreatePublicDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<byte>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartPublicDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  public static Offset<SF.Flat.PlayInstance.CharacterPublicDataChangedS2CEvt> EndCharacterPublicDataChangedS2CEvt(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SF.Flat.PlayInstance.CharacterPublicDataChangedS2CEvt>(o);
  }
}


static public class CharacterPublicDataChangedS2CEvtVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*PlayInstanceUid*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*PlayerId*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyVectorOfData(tablePos, 8 /*PublicData*/, 1 /*byte*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
