// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SF.Flat.PlayInstance
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct FindStreamCmd : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static FindStreamCmd GetRootAsFindStreamCmd(ByteBuffer _bb) { return GetRootAsFindStreamCmd(_bb, new FindStreamCmd()); }
  public static FindStreamCmd GetRootAsFindStreamCmd(ByteBuffer _bb, FindStreamCmd obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FindStreamCmd __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong Ticket { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public string StreamName { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetStreamNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetStreamNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetStreamNameArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<SF.Flat.PlayInstance.FindStreamCmd> CreateFindStreamCmd(FlatBufferBuilder builder,
      ulong ticket = 0,
      StringOffset stream_nameOffset = default(StringOffset)) {
    builder.StartTable(2);
    FindStreamCmd.AddTicket(builder, ticket);
    FindStreamCmd.AddStreamName(builder, stream_nameOffset);
    return FindStreamCmd.EndFindStreamCmd(builder);
  }

  public static void StartFindStreamCmd(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddTicket(FlatBufferBuilder builder, ulong ticket) { builder.AddUlong(0, ticket, 0); }
  public static void AddStreamName(FlatBufferBuilder builder, StringOffset streamNameOffset) { builder.AddOffset(1, streamNameOffset.Value, 0); }
  public static Offset<SF.Flat.PlayInstance.FindStreamCmd> EndFindStreamCmd(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SF.Flat.PlayInstance.FindStreamCmd>(o);
  }
}


static public class FindStreamCmdVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Ticket*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyString(tablePos, 6 /*StreamName*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
