// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SF.Flat.PlayInstance
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct GetStreamListCmd : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_7(); }
  public static GetStreamListCmd GetRootAsGetStreamListCmd(ByteBuffer _bb) { return GetRootAsGetStreamListCmd(_bb, new GetStreamListCmd()); }
  public static GetStreamListCmd GetRootAsGetStreamListCmd(ByteBuffer _bb, GetStreamListCmd obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public GetStreamListCmd __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong Ticket { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }

  public static Offset<SF.Flat.PlayInstance.GetStreamListCmd> CreateGetStreamListCmd(FlatBufferBuilder builder,
      ulong ticket = 0) {
    builder.StartTable(1);
    GetStreamListCmd.AddTicket(builder, ticket);
    return GetStreamListCmd.EndGetStreamListCmd(builder);
  }

  public static void StartGetStreamListCmd(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddTicket(FlatBufferBuilder builder, ulong ticket) { builder.AddUlong(0, ticket, 0); }
  public static Offset<SF.Flat.PlayInstance.GetStreamListCmd> EndGetStreamListCmd(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SF.Flat.PlayInstance.GetStreamListCmd>(o);
  }
}


static public class GetStreamListCmdVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Ticket*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
