// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SF.Flat.PlayInstance
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SendVoiceDataC2SEvt : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_7(); }
  public static SendVoiceDataC2SEvt GetRootAsSendVoiceDataC2SEvt(ByteBuffer _bb) { return GetRootAsSendVoiceDataC2SEvt(_bb, new SendVoiceDataC2SEvt()); }
  public static SendVoiceDataC2SEvt GetRootAsSendVoiceDataC2SEvt(ByteBuffer _bb, SendVoiceDataC2SEvt obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SendVoiceDataC2SEvt __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong PlayInstanceUid { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public ulong PlayerId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public ushort FrameIndex { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }
  public byte VoiceData(int j) { int o = __p.__offset(10); return o != 0 ? __p.bb.Get(__p.__vector(o) + j * 1) : (byte)0; }
  public int VoiceDataLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<byte> GetVoiceDataBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetVoiceDataBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetVoiceDataArray() { return __p.__vector_as_array<byte>(10); }

  public static Offset<SF.Flat.PlayInstance.SendVoiceDataC2SEvt> CreateSendVoiceDataC2SEvt(FlatBufferBuilder builder,
      ulong play_instance_uid = 0,
      ulong player_id = 0,
      ushort frame_index = 0,
      VectorOffset voice_dataOffset = default(VectorOffset)) {
    builder.StartTable(4);
    SendVoiceDataC2SEvt.AddPlayerId(builder, player_id);
    SendVoiceDataC2SEvt.AddPlayInstanceUid(builder, play_instance_uid);
    SendVoiceDataC2SEvt.AddVoiceData(builder, voice_dataOffset);
    SendVoiceDataC2SEvt.AddFrameIndex(builder, frame_index);
    return SendVoiceDataC2SEvt.EndSendVoiceDataC2SEvt(builder);
  }

  public static void StartSendVoiceDataC2SEvt(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddPlayInstanceUid(FlatBufferBuilder builder, ulong playInstanceUid) { builder.AddUlong(0, playInstanceUid, 0); }
  public static void AddPlayerId(FlatBufferBuilder builder, ulong playerId) { builder.AddUlong(1, playerId, 0); }
  public static void AddFrameIndex(FlatBufferBuilder builder, ushort frameIndex) { builder.AddUshort(2, frameIndex, 0); }
  public static void AddVoiceData(FlatBufferBuilder builder, VectorOffset voiceDataOffset) { builder.AddOffset(3, voiceDataOffset.Value, 0); }
  public static VectorOffset CreateVoiceDataVector(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddByte(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateVoiceDataVectorBlock(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateVoiceDataVectorBlock(FlatBufferBuilder builder, ArraySegment<byte> data) { builder.StartVector(1, data.Count, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateVoiceDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<byte>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartVoiceDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  public static Offset<SF.Flat.PlayInstance.SendVoiceDataC2SEvt> EndSendVoiceDataC2SEvt(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SF.Flat.PlayInstance.SendVoiceDataC2SEvt>(o);
  }
}


static public class SendVoiceDataC2SEvtVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*PlayInstanceUid*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*PlayerId*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 8 /*FrameIndex*/, 2 /*ushort*/, 2, false)
      && verifier.VerifyVectorOfData(tablePos, 10 /*VoiceData*/, 1 /*byte*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
