// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SF.Flat.PlayInstance
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SetCharacterPublicMessageCmd : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_7(); }
  public static SetCharacterPublicMessageCmd GetRootAsSetCharacterPublicMessageCmd(ByteBuffer _bb) { return GetRootAsSetCharacterPublicMessageCmd(_bb, new SetCharacterPublicMessageCmd()); }
  public static SetCharacterPublicMessageCmd GetRootAsSetCharacterPublicMessageCmd(ByteBuffer _bb, SetCharacterPublicMessageCmd obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SetCharacterPublicMessageCmd __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public SF.Flat.EntityUID? PlayInstanceUid { get { int o = __p.__offset(4); return o != 0 ? (SF.Flat.EntityUID?)(new SF.Flat.EntityUID()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public SF.Flat.AccountID? PlayerId { get { int o = __p.__offset(6); return o != 0 ? (SF.Flat.AccountID?)(new SF.Flat.AccountID()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public string PublicMessage { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetPublicMessageBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetPublicMessageBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetPublicMessageArray() { return __p.__vector_as_array<byte>(8); }

  public static void StartSetCharacterPublicMessageCmd(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddPlayInstanceUid(FlatBufferBuilder builder, Offset<SF.Flat.EntityUID> playInstanceUidOffset) { builder.AddStruct(0, playInstanceUidOffset.Value, 0); }
  public static void AddPlayerId(FlatBufferBuilder builder, Offset<SF.Flat.AccountID> playerIdOffset) { builder.AddStruct(1, playerIdOffset.Value, 0); }
  public static void AddPublicMessage(FlatBufferBuilder builder, StringOffset publicMessageOffset) { builder.AddOffset(2, publicMessageOffset.Value, 0); }
  public static Offset<SF.Flat.PlayInstance.SetCharacterPublicMessageCmd> EndSetCharacterPublicMessageCmd(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SF.Flat.PlayInstance.SetCharacterPublicMessageCmd>(o);
  }
}


static public class SetCharacterPublicMessageCmdVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*PlayInstanceUid*/, 4 /*SF.Flat.EntityUID*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*PlayerId*/, 16 /*SF.Flat.AccountID*/, 8, false)
      && verifier.VerifyString(tablePos, 8 /*PublicMessage*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
