// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SF.Flat.PlayInstance
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct WhiteboardSharingHasClosedS2CEvt : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static WhiteboardSharingHasClosedS2CEvt GetRootAsWhiteboardSharingHasClosedS2CEvt(ByteBuffer _bb) { return GetRootAsWhiteboardSharingHasClosedS2CEvt(_bb, new WhiteboardSharingHasClosedS2CEvt()); }
  public static WhiteboardSharingHasClosedS2CEvt GetRootAsWhiteboardSharingHasClosedS2CEvt(ByteBuffer _bb, WhiteboardSharingHasClosedS2CEvt obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public WhiteboardSharingHasClosedS2CEvt __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong PlayInstanceUid { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public ulong PlayerId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public ulong ClosedPlayerId { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }

  public static Offset<SF.Flat.PlayInstance.WhiteboardSharingHasClosedS2CEvt> CreateWhiteboardSharingHasClosedS2CEvt(FlatBufferBuilder builder,
      ulong play_instance_uid = 0,
      ulong player_id = 0,
      ulong closed_player_id = 0) {
    builder.StartTable(3);
    WhiteboardSharingHasClosedS2CEvt.AddClosedPlayerId(builder, closed_player_id);
    WhiteboardSharingHasClosedS2CEvt.AddPlayerId(builder, player_id);
    WhiteboardSharingHasClosedS2CEvt.AddPlayInstanceUid(builder, play_instance_uid);
    return WhiteboardSharingHasClosedS2CEvt.EndWhiteboardSharingHasClosedS2CEvt(builder);
  }

  public static void StartWhiteboardSharingHasClosedS2CEvt(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddPlayInstanceUid(FlatBufferBuilder builder, ulong playInstanceUid) { builder.AddUlong(0, playInstanceUid, 0); }
  public static void AddPlayerId(FlatBufferBuilder builder, ulong playerId) { builder.AddUlong(1, playerId, 0); }
  public static void AddClosedPlayerId(FlatBufferBuilder builder, ulong closedPlayerId) { builder.AddUlong(2, closedPlayerId, 0); }
  public static Offset<SF.Flat.PlayInstance.WhiteboardSharingHasClosedS2CEvt> EndWhiteboardSharingHasClosedS2CEvt(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SF.Flat.PlayInstance.WhiteboardSharingHasClosedS2CEvt>(o);
  }
}


static public class WhiteboardSharingHasClosedS2CEvtVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*PlayInstanceUid*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*PlayerId*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 8 /*ClosedPlayerId*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
