


set CMAKE_SYSTEM_NAME=Windows
set PROCESS_ARCHITECTUR=x64


if not exist build%CMAKE_SYSTEM_NAME% mkdir build%CMAKE_SYSTEM_NAME%
set BUILD_DIR=build%CMAKE_SYSTEM_NAME%



if not exist %BUILD_DIR% mkdir %BUILD_DIR%
REM if not exist %BUILD_DIR%\%PROCESS_ARCHITECTUR%Debug mkdir %BUILD_DIR%\%PROCESS_ARCHITECTUR%Debug
REM if not exist %BUILD_DIR%\%PROCESS_ARCHITECTUR%Release mkdir %BUILD_DIR%\%PROCESS_ARCHITECTUR%Release


cd %BUILD_DIR%\%PROCESS_ARCHITECTUR%

cmake ../../ -G "Visual Studio 15 2017" -A %PROCESS_ARCHITECTUR% 




pause


