
set CMAKE_SYSTEM_NAME=Windows
set PROCESS_ARCHITECTUR=x64
set BUILD_DIR_BASE=build%CMAKE_SYSTEM_NAME%\%PROCESS_ARCHITECTUR%

call build\FindVC.cmd
call SetupSDKPath.cmd

rem for %%I in (.) do set SF_DIR=%%~nxI
set SF_DIR=%~dp0


if not exist build%CMAKE_SYSTEM_NAME% mkdir build%CMAKE_SYSTEM_NAME%


set CMAKE_BUILD_TYPE=Debug
set BUILD_DIR=%BUILD_DIR_BASE%%CMAKE_BUILD_TYPE%

if not exist %BUILD_DIR% mkdir %BUILD_DIR%

cd %BUILD_DIR%

cmake ../../ -G %VCCMAKEGENERATOR% -A %PROCESS_ARCHITECTUR%  ^
	-DCMAKE_INSTALL_PREFIX=%SF_DIR%/build%CMAKE_SYSTEM_NAME%/%PROCESS_ARCHITECTUR%%CMAKE_BUILD_TYPE% ^
	-DCMAKE_SYSTEM_NAME=%CMAKE_SYSTEM_NAME% ^
	-DCMAKE_BUILD_TYPE=%CMAKE_BUILD_TYPE% 

cd ..\..

set CMAKE_BUILD_TYPE=Release
set BUILD_DIR=%BUILD_DIR_BASE%%CMAKE_BUILD_TYPE%

if not exist %BUILD_DIR% mkdir %BUILD_DIR%

cd %BUILD_DIR%

cmake ../../ -G %VCCMAKEGENERATOR% -A %PROCESS_ARCHITECTUR%  ^
	-DCMAKE_INSTALL_PREFIX=%SF_DIR%/build%CMAKE_SYSTEM_NAME%/%PROCESS_ARCHITECTUR%%CMAKE_BUILD_TYPE% ^
	-DCMAKE_SYSTEM_NAME=%CMAKE_SYSTEM_NAME% ^
	-DCMAKE_BUILD_TYPE=%CMAKE_BUILD_TYPE% 

cd ..

cd ..

cd %~dp0

if not "%1" == "nopause" pause

