////////////////////////////////////////////////////////////////////////////////
// 
// CopyRight (c) Kyungkun Ko
// 
// Author : KyungKun Ko
//
// Description : Autogenerated header, SF
//
////////////////////////////////////////////////////////////////////////////////

#pragma once
#include "SFTypedefs.h"
#include "ResultCode/ResultTable.h"
#include "ResultCode/SFResultCodeSystem.h"



namespace SF {
namespace ResultCode {

	void InitializeResultCodeSystem() {

		auto& codeMap = ResultTable::GetOrAddFacility(0);

		codeMap.Insert(SUCCESS, {"SUCCESS", "SUCCESS"});
		codeMap.Insert(SUCCESS_FALSE, {"SUCCESS_FALSE", "SUCCESS_FALSE"});
		codeMap.Insert(SUCCESS_YIELD, {"SUCCESS_YIELD", "SUCCESS_YIELD"});
		codeMap.Insert(INVALID_POINTER, {"INVALID_POINTER", "INVALID_POINTER"});
		codeMap.Insert(FAIL, {"FAIL", "FAIL"});
		codeMap.Insert(NOT_IMPLEMENTED, {"NOT_IMPLEMENTED", "NOT_IMPLEMENTED"});
		codeMap.Insert(OUT_OF_MEMORY, {"OUT_OF_MEMORY", "OUT_OF_MEMORY"});
		codeMap.Insert(UNEXPECTED, {"UNEXPECTED", "UNEXPECTED"});
		codeMap.Insert(INVALID_ARG, {"INVALID_ARG", "INVALID_ARG"});
		codeMap.Insert(NO_DATA_EXIST, {"NO_DATA_EXIST", "NO_DATA_EXIST"});

	}//InitializeResultCode 
}//namespace ResultCode 
}//namespace SF 



