////////////////////////////////////////////////////////////////////////////////
// 
// CopyRight (c) Kyungkun Ko
// 
// Author : KyungKun Ko
//
// Description : Autogenerated file, Login
//
////////////////////////////////////////////////////////////////////////////////

using System;


namespace SF {
	public partial struct ResultCode {

		// Invalid username 
		public static readonly Result LOGIN_INVALID_USERNAME =              new Result(unchecked((int)0xE7060000)); 

		// Invalid password 
		public static readonly Result LOGIN_INVALID_PASSWORD =              new Result(unchecked((int)0xE7060001)); 

		// Already logged in 
		public static readonly Result LOGIN_ALREADY_LOGGEDIN =              new Result(unchecked((int)0xE7060002)); 

		// Already logged in at another place, and failed to kick 
		public static readonly Result LOGIN_ALREADY_LOGGEDIN_OTHERPLACE =   new Result(unchecked((int)0xE7060003)); 

		// Invalid user signature 
		public static readonly Result LOGIN_INVALID_SIGNATURE =             new Result(unchecked((int)0xE7060004)); 

		// The user doesn't have app ownership 
		public static readonly Result LOGIN_NO_APP_OWNERSHIP =              new Result(unchecked((int)0xE7060005)); 

		// The user is blocked 
		public static readonly Result LOGIN_ACCOUNT_BLOCKED =               new Result(unchecked((int)0xE7060006)); 

		// The user is not exist 
		public static readonly Result LOGIN_ACCOUNT_DOES_NOT_EXIST =        new Result(unchecked((int)0xE7060007)); 

		// The user's platform login is invalid 
		public static readonly Result LOGIN_INVALID_PLATFORM_LOGIN =        new Result(unchecked((int)0xE7060008)); 

	}
}



