

set CMAKE_SYSTEM_NAME=Windows
set PROCESS_ARCHITECTUR=x64
set SRC_BASE=libwebsockets


rem if not exist %SRC_BASE%  call download.cmd


call ..\..\FindVC.cmd

if not exist %CMAKE_SYSTEM_NAME% mkdir %CMAKE_SYSTEM_NAME%
if not exist %CMAKE_SYSTEM_NAME%\Debug mkdir %CMAKE_SYSTEM_NAME%\Debug
if not exist %CMAKE_SYSTEM_NAME%\RelWithDebInfo mkdir %CMAKE_SYSTEM_NAME%\RelWithDebInfo

cd %CMAKE_SYSTEM_NAME%

rem disabling -DLWS_WITH_THREADPOOL=1, it isn't supported well

set CONFIGURATION=Debug
cd %CONFIGURATION%
cmake ../../%SRC_BASE% -G %VCCMAKEGENERATOR% -A %PROCESS_ARCHITECTUR%  ^
	-DCMAKE_INSTALL_PREFIX=../../../../%CMAKE_SYSTEM_NAME%/%CONFIGURATION%  -DCMAKE_SYSTEM_NAME=%CMAKE_SYSTEM_NAME% ^
	-DLWS_WITHOUT_EXTENSIONS=0 -DLWS_WITH_THREADPOOL=1 -DLWS_WITH_HTTP_STREAM_COMPRESSION=1 -DLWS_IPV6=1 -DLWS_WITH_SOCKS5=1 ^
	-DLWS_WITH_ZLIB=1 -DLWS_WITH_BUNDLED_ZLIB=0 -DLWS_WITH_LIBEVENT=1 -DLWS_WITH_SHARED=0 ^
	-DLWS_EXT_PTHREAD_INCLUDE_DIR=../../../../Windows/%CONFIGURATION%/include ^
	-DLWS_EXT_PTHREAD_LIBRARIES=../../../../Windows/%CONFIGURATION%/lib/SFWinport.lib ^
	-DLWS_WITH_HTTP2=1 -DLWS_OPENSSL_INCLUDE_DIRS=../../../../Windows/Common/include ^
	-DLWS_OPENSSL_LIBRARIES="../../../../Windows/Common/lib/libssl.lib;../../../../Windows/Common/lib/libcrypto.lib"

cd ..

set CONFIGURATION=RelWithDebInfo
cd %CONFIGURATION%
cmake ../../%SRC_BASE% -G %VCCMAKEGENERATOR% -A %PROCESS_ARCHITECTUR%  ^
	-DCMAKE_INSTALL_PREFIX=../../../../%CMAKE_SYSTEM_NAME%/%CONFIGURATION%  -DCMAKE_SYSTEM_NAME=%CMAKE_SYSTEM_NAME% ^
	-DLWS_WITHOUT_EXTENSIONS=0  -DLWS_WITH_THREADPOOL=1  -DLWS_WITH_HTTP_STREAM_COMPRESSION=1 -DLWS_IPV6=1 -DLWS_WITH_SOCKS5=1^
	-DLWS_WITH_ZLIB=1 -DLWS_WITH_BUNDLED_ZLIB=0 -DLWS_WITH_LIBEVENT=1 -DLWS_WITH_SHARED=0 ^
	-DLWS_EXT_PTHREAD_INCLUDE_DIR=../../../../Windows/%CONFIGURATION%/include ^
	-DLWS_EXT_PTHREAD_LIBRARIES=../../../../Windows/%CONFIGURATION%/lib/SFWinport.lib ^
	-DLWS_WITH_HTTP2=1 -DLWS_OPENSSL_INCLUDE_DIRS=../../../../Windows/Common/include ^
	-DLWS_OPENSSL_LIBRARIES="../../../../Windows/Common/lib/libssl.lib;../../../../Windows/Common/lib/libcrypto.lib"

cd ..
cd ..
