// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SF.Flat.Generic
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct MessageBusSendRes : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_7(); }
  public static MessageBusSendRes GetRootAsMessageBusSendRes(ByteBuffer _bb) { return GetRootAsMessageBusSendRes(_bb, new MessageBusSendRes()); }
  public static MessageBusSendRes GetRootAsMessageBusSendRes(ByteBuffer _bb, MessageBusSendRes obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public MessageBusSendRes __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string DestChannel { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDestChannelBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetDestChannelBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetDestChannelArray() { return __p.__vector_as_array<byte>(4); }
  public byte MessageData(int j) { int o = __p.__offset(6); return o != 0 ? __p.bb.Get(__p.__vector(o) + j * 1) : (byte)0; }
  public int MessageDataLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<byte> GetMessageDataBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetMessageDataBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetMessageDataArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<SF.Flat.Generic.MessageBusSendRes> CreateMessageBusSendRes(FlatBufferBuilder builder,
      StringOffset dest_channelOffset = default(StringOffset),
      VectorOffset message_dataOffset = default(VectorOffset)) {
    builder.StartTable(2);
    MessageBusSendRes.AddMessageData(builder, message_dataOffset);
    MessageBusSendRes.AddDestChannel(builder, dest_channelOffset);
    return MessageBusSendRes.EndMessageBusSendRes(builder);
  }

  public static void StartMessageBusSendRes(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddDestChannel(FlatBufferBuilder builder, StringOffset destChannelOffset) { builder.AddOffset(0, destChannelOffset.Value, 0); }
  public static void AddMessageData(FlatBufferBuilder builder, VectorOffset messageDataOffset) { builder.AddOffset(1, messageDataOffset.Value, 0); }
  public static VectorOffset CreateMessageDataVector(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddByte(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateMessageDataVectorBlock(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateMessageDataVectorBlock(FlatBufferBuilder builder, ArraySegment<byte> data) { builder.StartVector(1, data.Count, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateMessageDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<byte>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartMessageDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  public static Offset<SF.Flat.Generic.MessageBusSendRes> EndMessageBusSendRes(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SF.Flat.Generic.MessageBusSendRes>(o);
  }
}


static public class MessageBusSendResVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*DestChannel*/, false)
      && verifier.VerifyVectorOfData(tablePos, 6 /*MessageData*/, 1 /*byte*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
