// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SF.Flat.Generic
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct MessageBusListenRes : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_7(); }
  public static MessageBusListenRes GetRootAsMessageBusListenRes(ByteBuffer _bb) { return GetRootAsMessageBusListenRes(_bb, new MessageBusListenRes()); }
  public static MessageBusListenRes GetRootAsMessageBusListenRes(ByteBuffer _bb, MessageBusListenRes obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public MessageBusListenRes __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string ChannelToListen { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetChannelToListenBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetChannelToListenBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetChannelToListenArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<SF.Flat.Generic.MessageBusListenRes> CreateMessageBusListenRes(FlatBufferBuilder builder,
      StringOffset channel_to_listenOffset = default(StringOffset)) {
    builder.StartTable(1);
    MessageBusListenRes.AddChannelToListen(builder, channel_to_listenOffset);
    return MessageBusListenRes.EndMessageBusListenRes(builder);
  }

  public static void StartMessageBusListenRes(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddChannelToListen(FlatBufferBuilder builder, StringOffset channelToListenOffset) { builder.AddOffset(0, channelToListenOffset.Value, 0); }
  public static Offset<SF.Flat.Generic.MessageBusListenRes> EndMessageBusListenRes(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SF.Flat.Generic.MessageBusListenRes>(o);
  }
}


static public class MessageBusListenResVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*ChannelToListen*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
