// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SF.Flat.Generic
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct PostLogDataRes : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_7(); }
  public static PostLogDataRes GetRootAsPostLogDataRes(ByteBuffer _bb) { return GetRootAsPostLogDataRes(_bb, new PostLogDataRes()); }
  public static PostLogDataRes GetRootAsPostLogDataRes(ByteBuffer _bb, PostLogDataRes obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyPostLogDataRes(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, PostLogDataResVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PostLogDataRes __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartPostLogDataRes(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<SF.Flat.Generic.PostLogDataRes> EndPostLogDataRes(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SF.Flat.Generic.PostLogDataRes>(o);
  }
  public static void FinishPostLogDataResBuffer(FlatBufferBuilder builder, Offset<SF.Flat.Generic.PostLogDataRes> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedPostLogDataResBuffer(FlatBufferBuilder builder, Offset<SF.Flat.Generic.PostLogDataRes> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class PostLogDataResVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
