

set CMAKE_SYSTEM_NAME=Windows
set PROCESS_ARCHITECTUR=x64
set SRC_PATH=libevent-2.1.12-stable

if not exist %SRC_PATH%.tar.gz (
	call download.cmd
)

call ..\..\FindVC.cmd

if not exist %CMAKE_SYSTEM_NAME% mkdir %CMAKE_SYSTEM_NAME%
if not exist %CMAKE_SYSTEM_NAME%\Debug mkdir %CMAKE_SYSTEM_NAME%\Debug
if not exist %CMAKE_SYSTEM_NAME%\RelWithDebInfo mkdir %CMAKE_SYSTEM_NAME%\RelWithDebInfo

cd %CMAKE_SYSTEM_NAME%


set CONFIGURATION=Debug
cd %CONFIGURATION%
cmake ../../%SRC_PATH% -G %VCCMAKEGENERATOR% -A %PROCESS_ARCHITECTUR%  ^
	-DCMAKE_INSTALL_PREFIX=../../../../%CMAKE_SYSTEM_NAME%/%CONFIGURATION%  -DCMAKE_SYSTEM_NAME=%CMAKE_SYSTEM_NAME% -DCMAKE_BUILD_TYPE=%CONFIGURATION% ^
	-DEVENT__DISABLE_TESTS=1 -DEVENT__DISABLE_OPENSSL=1 -DEVENT__LIBRARY_TYPE=STATIC


cd ..

set CONFIGURATION=RelWithDebInfo
cd %CONFIGURATION%
cmake ../../%SRC_PATH% -G %VCCMAKEGENERATOR% -A %PROCESS_ARCHITECTUR%  ^
	-DCMAKE_INSTALL_PREFIX=../../../../%CMAKE_SYSTEM_NAME%/%CONFIGURATION%  -DCMAKE_SYSTEM_NAME=%CMAKE_SYSTEM_NAME% -DCMAKE_BUILD_TYPE=%CONFIGURATION% ^
	-DEVENT__DISABLE_TESTS=1 -DEVENT__DISABLE_OPENSSL=1 -DEVENT__LIBRARY_TYPE=STATIC


cd ..
cd ..
