

export CMAKE_SYSTEM_NAME=Linux
export PROCESS_ARCHITECTUR=x64
export SRC_PATH=libevent-2.1.12-stable


if [ ! -f "$SRC_PATH.tar.gz" ]; then
	./download.sh
fi

if [ ! -d "$CMAKE_SYSTEM_NAME" ]; then
	mkdir $CMAKE_SYSTEM_NAME
fi

if [ ! -d "$CMAKE_SYSTEM_NAME/Debug" ]; then
	mkdir $CMAKE_SYSTEM_NAME/Debug
fi

if [ ! -d "$CMAKE_SYSTEM_NAME/RelWithDebInfo" ]; then
	mkdir $CMAKE_SYSTEM_NAME/RelWithDebInfo
fi


pushd $CMAKE_SYSTEM_NAME



export CONFIGURATION=Debug
pushd $CONFIGURATION
cmake ../../$SRC_PATH -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=$CONFIGURATION  \
	-DCMAKE_INSTALL_PREFIX=../../../../$CMAKE_SYSTEM_NAME/$CONFIGURATION  -DCMAKE_SYSTEM_NAME=$CMAKE_SYSTEM_NAME  -DCMAKE_BUILD_TYPE=$CONFIGURATION \
	-DEVENT__DISABLE_TESTS=1 -DEVENT__DISABLE_OPENSSL=1 -DEVENT__LIBRARY_TYPE=STATIC

popd


export CONFIGURATION=RelWithDebInfo
pushd $CONFIGURATION
cmake ../../$SRC_PATH -G "Unix Makefiles"  -DCMAKE_BUILD_TYPE=$CONFIGURATION \
	-DCMAKE_INSTALL_PREFIX=../../../../$CMAKE_SYSTEM_NAME/$CONFIGURATION  -DCMAKE_SYSTEM_NAME=$CMAKE_SYSTEM_NAME  -DCMAKE_BUILD_TYPE=$CONFIGURATION \
	-DEVENT__DISABLE_TESTS=1 -DEVENT__DISABLE_OPENSSL=1 -DEVENT__LIBRARY_TYPE=STATIC

popd
popd


#export LD_LIBRARY_PATH=$SavedLinkDir

