

export CMAKE_SYSTEM_NAME=Linux
export PROCESS_ARCHITECTUR=x64
export SRC_BASE=libevent-2.1.12-stable
export SRC_PATH=../../../src/libevent/$SRC_BASE
export INTERMEDIATE_DIR=../../$CMAKE_SYSTEM_NAME/libevent


if [ ! -f "$SRC_PATH.tar.gz" ]; then
	./download.sh
fi

if [ ! -d "$INTERMEDIATE_DIR" ]; then
	mkdir $INTERMEDIATE_DIR
fi

if [ ! -d "$INTERMEDIATE_DIR/Debug" ]; then
	mkdir $INTERMEDIATE_DIR/Debug
fi

if [ ! -d "$INTERMEDIATE_DIR/RelWithDebInfo" ]; then
	mkdir $INTERMEDIATE_DIR/RelWithDebInfo
fi


pushd $INTERMEDIATE_DIR



export CONFIGURATION=Debug
pushd $CONFIGURATION
cmake $SRC_PATH -G "Ninja" -DCMAKE_BUILD_TYPE=$CONFIGURATION  \
	-DCMAKE_INSTALL_PREFIX=../../$CONFIGURATION  -DCMAKE_SYSTEM_NAME=$CMAKE_SYSTEM_NAME  -DCMAKE_BUILD_TYPE=$CONFIGURATION \
	-DEVENT__DISABLE_TESTS=1 -DEVENT__DISABLE_OPENSSL=1 -DEVENT__LIBRARY_TYPE=STATIC

popd


export CONFIGURATION=RelWithDebInfo
pushd $CONFIGURATION
cmake $SRC_PATH -G "Ninja"  -DCMAKE_BUILD_TYPE=$CONFIGURATION \
	-DCMAKE_INSTALL_PREFIX=../../$CONFIGURATION  -DCMAKE_SYSTEM_NAME=$CMAKE_SYSTEM_NAME  -DCMAKE_BUILD_TYPE=$CONFIGURATION \
	-DEVENT__DISABLE_TESTS=1 -DEVENT__DISABLE_OPENSSL=1 -DEVENT__LIBRARY_TYPE=STATIC

popd
popd


#export LD_LIBRARY_PATH=$SavedLinkDir

