

export CMAKE_SYSTEM_NAME=Linux
export PROCESS_ARCHITECTUR=x64


if [ ! -d "build$CMAKE_SYSTEM_NAME" ]; then
	mkdir build$CMAKE_SYSTEM_NAME
fi

if [ ! -d "build$CMAKE_SYSTEM_NAME/Debug" ]; then
	mkdir build$CMAKE_SYSTEM_NAME/Debug
fi

if [ ! -d "build$CMAKE_SYSTEM_NAME/RelWithDebInfo" ]; then
	mkdir build$CMAKE_SYSTEM_NAME/RelWithDebInfo
fi


pushd build$CMAKE_SYSTEM_NAME



export CONFIGURATION=Debug
pushd $CONFIGURATION
cmake ../../1.17 -G "Ninja" -DCMAKE_BUILD_TYPE=$CONFIGURATION  \
	-DCMAKE_INSTALL_PREFIX=../../../../$CMAKE_SYSTEM_NAME/$CONFIGURATION  -DCMAKE_SYSTEM_NAME=$CMAKE_SYSTEM_NAME \
	-DENABLE_TESTS=OFF -DENABLE_EXAMPLES=OFF \
	-DENABLE_STATIC=ON -DENABLE_ZLIB=BUNDLED -DENABLE_BSON=ON -DENABLE_MONGODB_AWS_AUTH=OFF 

popd


export CONFIGURATION=RelWithDebInfo
pushd $CONFIGURATION
cmake ../../1.17 -G "Ninja"  -DCMAKE_BUILD_TYPE=$CONFIGURATION \
	-DCMAKE_INSTALL_PREFIX=../../../../$CMAKE_SYSTEM_NAME/$CONFIGURATION  -DCMAKE_SYSTEM_NAME=$CMAKE_SYSTEM_NAME \
	-DENABLE_TESTS=OFF -DENABLE_EXAMPLES=OFF \
	-DENABLE_STATIC=ON -DENABLE_ZLIB=BUNDLED -DENABLE_BSON=ON -DENABLE_MONGODB_AWS_AUTH=OFF 

popd
popd




