

export CMAKE_SYSTEM_NAME=Linux
export PROCESS_ARCHITECTUR=x64
export SRC_PATH=../../../src/mongoc/1.17
export INTERMEDIATE_DIR=../../$CMAKE_SYSTEM_NAME/mongoc


if [ ! -d "$INTERMEDIATE_DIR" ]; then
	mkdir $INTERMEDIATE_DIR
fi

if [ ! -d "$INTERMEDIATE_DIR/Debug" ]; then
	mkdir $INTERMEDIATE_DIR/Debug
fi

if [ ! -d "$INTERMEDIATE_DIR/RelWithDebInfo" ]; then
	mkdir $INTERMEDIATE_DIR/RelWithDebInfo
fi


pushd $INTERMEDIATE_DIR



export CONFIGURATION=Debug
pushd $CONFIGURATION
cmake $SRC_PATH -G "Ninja" -DCMAKE_BUILD_TYPE=$CONFIGURATION  \
	-DCMAKE_INSTALL_PREFIX=../../$CONFIGURATION  -DCMAKE_SYSTEM_NAME=$CMAKE_SYSTEM_NAME \
	-DENABLE_TESTS=OFF -DENABLE_EXAMPLES=OFF \
	-DENABLE_STATIC=ON -DENABLE_ZLIB=BUNDLED -DENABLE_BSON=ON -DENABLE_MONGODB_AWS_AUTH=OFF 

popd


export CONFIGURATION=RelWithDebInfo
pushd $CONFIGURATION
cmake $SRC_PATH -G "Ninja"  -DCMAKE_BUILD_TYPE=$CONFIGURATION \
	-DCMAKE_INSTALL_PREFIX=../../$CONFIGURATION  -DCMAKE_SYSTEM_NAME=$CMAKE_SYSTEM_NAME \
	-DENABLE_TESTS=OFF -DENABLE_EXAMPLES=OFF \
	-DENABLE_STATIC=ON -DENABLE_ZLIB=BUNDLED -DENABLE_BSON=ON -DENABLE_MONGODB_AWS_AUTH=OFF 

popd
popd




