

set CMAKE_SYSTEM_NAME=Windows
set PROCESS_ARCHITECTUR=x64
set SRC_PATH=../../../src/mongoc/1.17
set INTERMEDIATE_DIR=..\..\%CMAKE_SYSTEM_NAME%\mongoc


call ..\..\FindVC.cmd

if not exist %INTERMEDIATE_DIR% mkdir %INTERMEDIATE_DIR%
if not exist %INTERMEDIATE_DIR%\Debug mkdir %INTERMEDIATE_DIR%\Debug
if not exist %INTERMEDIATE_DIR%\RelWithDebInfo mkdir %INTERMEDIATE_DIR%\RelWithDebInfo

cd %INTERMEDIATE_DIR%


set CONFIGURATION=Debug
cd %CONFIGURATION%
cmake %SRC_PATH% -G %VCCMAKEGENERATOR% -A %PROCESS_ARCHITECTUR%  ^
	-DCMAKE_INSTALL_PREFIX=../../%CONFIGURATION%  -DCMAKE_SYSTEM_NAME=%CMAKE_SYSTEM_NAME% ^
	-DENABLE_TESTS=OFF -DENABLE_EXAMPLES=OFF ^
	-DENABLE_STATIC=ON -DENABLE_ZLIB=SYSTEM -DENABLE_BSON=ON -DZLIB_ROOT=../../%CONFIGURATION% -DZLIB_LIBRARY=../../../../%CONFIGURATION%/lib/zlib ^
	-DCMAKE_APPBUNDLE_PATH=../../%CONFIGURATION%;../../%CONFIGURATION%lib;

cd ..

set CONFIGURATION=RelWithDebInfo
cd %CONFIGURATION%
cmake %SRC_PATH% -G %VCCMAKEGENERATOR% -A %PROCESS_ARCHITECTUR%  ^
	-DCMAKE_INSTALL_PREFIX=../../%CONFIGURATION%  -DCMAKE_SYSTEM_NAME=%CMAKE_SYSTEM_NAME% ^
	-DENABLE_TESTS=OFF -DENABLE_EXAMPLES=OFF ^
	-DENABLE_STATIC=ON -DENABLE_ZLIB=SYSTEM -DENABLE_BSON=ON -DZLIB_ROOT=../../%CONFIGURATION% -DZLIB_LIBRARY=../../../../%CONFIGURATION%/lib/zlib ^
	-DCMAKE_APPBUNDLE_PATH=../../%CONFIGURATION%;../../%CONFIGURATION%lib;

cd %~dp0
