////////////////////////////////////////////////////////////////////////////////
// 
// CopyRight (c) 2016 Kyungkun Ko
// 
// Author : KyungKun Ko
//
// Description : Autogenerated header, Engine
//
////////////////////////////////////////////////////////////////////////////////

#pragma once
#include <stdint.h>



namespace SF {
	namespace ResultCode {



			// Engine initialization is failed 
			constexpr Result 			ENGINE_INITIALIZATION_FAILED                                       ((int32_t)0xE7020000L);

			// Invalid configuration 
			constexpr Result 			ENGINE_INVALID_CONFIG                                              ((int32_t)0xE7020001L);

			// Connection failed 
			constexpr Result 			ENGINE_CONNECTION_FAILED                                           ((int32_t)0xE7020002L);

			// Connectionlost 
			constexpr Result 			ENGINE_CONNECTION_LOST                                             ((int32_t)0xE7020003L);

			// Invalid character data 
			constexpr Result 			ENGINE_INVALID_CHARACTER                                           ((int32_t)0xE7020004L);

			// Invalid table id 
			constexpr Result 			ENGINE_INVALID_TABLE_ID                                            ((int32_t)0xE7020005L);

	void InitializeResultCodeEngine();

	}//namespace ResultCode 
}//namespace SF 





