////////////////////////////////////////////////////////////////////////////////
// 
// CopyRight (c) 2016 Kyungkun Ko
// 
// Author : KyungKun Ko
//
// Description : Autogenerated header, Login
//
////////////////////////////////////////////////////////////////////////////////

#pragma once
#include <stdint.h>



namespace SF {
	namespace ResultCode {



			// Invalid username 
			constexpr Result 			LOGIN_INVALID_USERNAME                                             ((int32_t)0xE7060000L);

			// Invalid password 
			constexpr Result 			LOGIN_INVALID_PASSWORD                                             ((int32_t)0xE7060001L);

			// Already logged in 
			constexpr Result 			LOGIN_ALREADY_LOGGEDIN                                             ((int32_t)0xE7060002L);

			// Already logged in at another place, and failed to kick 
			constexpr Result 			LOGIN_ALREADY_LOGGEDIN_OTHERPLACE                                  ((int32_t)0xE7060003L);

			// Invalid user signature 
			constexpr Result 			LOGIN_INVALID_SIGNATURE                                            ((int32_t)0xE7060004L);

			// The user doesn't have app ownership 
			constexpr Result 			LOGIN_NO_APP_OWNERSHIP                                             ((int32_t)0xE7060005L);

			// The user is blocked 
			constexpr Result 			LOGIN_ACCOUNT_BLOCKED                                              ((int32_t)0xE7060006L);

			// The user is not exist 
			constexpr Result 			LOGIN_ACCOUNT_DOES_NOT_EXIST                                       ((int32_t)0xE7060007L);

			// The user's platform login is invalid 
			constexpr Result 			LOGIN_INVALID_PLATFORM_LOGIN                                       ((int32_t)0xE7060008L);

			// The user doesn't have enough priviledge 
			constexpr Result 			LOGIN_NOT_ENOUGH_PRIVILEDGE                                        ((int32_t)0xE7060009L);

	void InitializeResultCodeLogin();

	}//namespace ResultCode 
}//namespace SF 





