////////////////////////////////////////////////////////////////////////////////
// 
// CopyRight (c) Kyungkun Ko
// 
// Author : KyungKun Ko
//
// Description : Autogenerated header, Engine
//
////////////////////////////////////////////////////////////////////////////////

#include "SFTypedefs.h"
#include "ResultCode/SFResultTable.h"
#include "ResultCode/SFResultCodeEngine.h"



namespace SF {
namespace ResultCode {

	void InitializeResultCodeEngine() {

		auto& codeMap = ResultTable::GetOrAddFacility(1794);
		codeMap.Insert((uint32_t)			ENGINE_INITIALIZATION_FAILED        , {"			ENGINE_INITIALIZATION_FAILED        ", "Engine initialization is failed"});
		codeMap.Insert((uint32_t)			ENGINE_INVALID_CONFIG        , {"			ENGINE_INVALID_CONFIG        ", "Invalid configuration"});
		codeMap.Insert((uint32_t)			ENGINE_CONNECTION_FAILED        , {"			ENGINE_CONNECTION_FAILED        ", "Connection failed"});
		codeMap.Insert((uint32_t)			ENGINE_CONNECTION_LOST        , {"			ENGINE_CONNECTION_LOST        ", "Connectionlost"});
		codeMap.Insert((uint32_t)			ENGINE_INVALID_CHARACTER        , {"			ENGINE_INVALID_CHARACTER        ", "Invalid character data"});
		codeMap.Insert((uint32_t)			ENGINE_INVALID_TABLE_ID        , {"			ENGINE_INVALID_TABLE_ID        ", "Invalid table id"});
		codeMap.Insert((uint32_t)			ENGINE_INVALID_PLATFORM        , {"			ENGINE_INVALID_PLATFORM        ", "Invalid platform"});
		codeMap.Insert((uint32_t)			ENGINE_ALREADY_USED_ITEM        , {"			ENGINE_ALREADY_USED_ITEM        ", "Already Used Item"});
		codeMap.Insert((uint32_t)			ENGINE_ALREADY_USED_KEY        , {"			ENGINE_ALREADY_USED_KEY        ", "Already Used Key"});
		codeMap.Insert((uint32_t)			ENGINE_INVALID_ONLINE_SESSION        , {"			ENGINE_INVALID_ONLINE_SESSION        ", "Invalid online session. probably kicked/expired"});
		codeMap.Insert((uint32_t)			ENGINE_INVALID_SESSION_TOKEN        , {"			ENGINE_INVALID_SESSION_TOKEN        ", "Invalid session token. probably dupe login"});
		codeMap.Insert((uint32_t)			ENGINE_INVALID_GAME_SESSION        , {"			ENGINE_INVALID_GAME_SESSION        ", "Invalid session GameUID. probably dupe login"});
		codeMap.Insert((uint32_t)			ENGINE_INVALIDD_TITLE_GUID        , {"			ENGINE_INVALIDD_TITLE_GUID        ", "Invalid title guid"});
		codeMap.Insert((uint32_t)			ENGINE_INVALIDD_TITLE_ENV        , {"			ENGINE_INVALIDD_TITLE_ENV        ", "Invalid titile env"});

	}//InitializeResultCode 
}//namespace ResultCode 
}//namespace SF 



