// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SFTYPES_SF_FLAT_H_
#define FLATBUFFERS_GENERATED_SFTYPES_SF_FLAT_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

namespace SF {
namespace Flat {

struct TimeSpan;

struct GenericError;
struct GenericErrorBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) TimeSpan FLATBUFFERS_FINAL_CLASS {
 private:
  int32_t hours_;
  int32_t minutes_;
  int32_t seconds_;

 public:
  struct Traits;
  TimeSpan()
      : hours_(0),
        minutes_(0),
        seconds_(0) {
  }
  TimeSpan(int32_t _hours, int32_t _minutes, int32_t _seconds)
      : hours_(::flatbuffers::EndianScalar(_hours)),
        minutes_(::flatbuffers::EndianScalar(_minutes)),
        seconds_(::flatbuffers::EndianScalar(_seconds)) {
  }
  int32_t hours() const {
    return ::flatbuffers::EndianScalar(hours_);
  }
  int32_t minutes() const {
    return ::flatbuffers::EndianScalar(minutes_);
  }
  int32_t seconds() const {
    return ::flatbuffers::EndianScalar(seconds_);
  }
  template<size_t Index>
  auto get_field() const {
         if constexpr (Index == 0) return hours();
    else if constexpr (Index == 1) return minutes();
    else if constexpr (Index == 2) return seconds();
    else static_assert(Index != Index, "Invalid Field Index");
  }
};
FLATBUFFERS_STRUCT_END(TimeSpan, 12);

struct TimeSpan::Traits {
  using type = TimeSpan;
  static constexpr auto name = "TimeSpan";
  static constexpr auto fully_qualified_name = "SF.Flat.TimeSpan";
  static constexpr size_t fields_number = 3;
  static constexpr std::array<const char *, fields_number> field_names = {
    "hours",
    "minutes",
    "seconds"
  };
  template<size_t Index>
  using FieldType = decltype(std::declval<type>().get_field<Index>());
};

struct GenericError FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef GenericErrorBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_REASON = 4
  };
  const ::flatbuffers::String *reason() const {
    return GetPointer<const ::flatbuffers::String *>(VT_REASON);
  }
  template<size_t Index>
  auto get_field() const {
         if constexpr (Index == 0) return reason();
    else static_assert(Index != Index, "Invalid Field Index");
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_REASON) &&
           verifier.VerifyString(reason()) &&
           verifier.EndTable();
  }
};

struct GenericErrorBuilder {
  typedef GenericError Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_reason(::flatbuffers::Offset<::flatbuffers::String> reason) {
    fbb_.AddOffset(GenericError::VT_REASON, reason);
  }
  explicit GenericErrorBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<GenericError> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<GenericError>(end);
    fbb_.Required(o, GenericError::VT_REASON);
    return o;
  }
};

inline ::flatbuffers::Offset<GenericError> CreateGenericError(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> reason = 0) {
  GenericErrorBuilder builder_(_fbb);
  builder_.add_reason(reason);
  return builder_.Finish();
}

struct GenericError::Traits {
  using type = GenericError;
  static auto constexpr Create = CreateGenericError;
  static constexpr auto name = "GenericError";
  static constexpr auto fully_qualified_name = "SF.Flat.GenericError";
  static constexpr size_t fields_number = 1;
  static constexpr std::array<const char *, fields_number> field_names = {
    "reason"
  };
  template<size_t Index>
  using FieldType = decltype(std::declval<type>().get_field<Index>());
};

inline ::flatbuffers::Offset<GenericError> CreateGenericErrorDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *reason = nullptr) {
  auto reason__ = reason ? _fbb.CreateString(reason) : 0;
  return SF::Flat::CreateGenericError(
      _fbb,
      reason__);
}

}  // namespace Flat
}  // namespace SF

#endif  // FLATBUFFERS_GENERATED_SFTYPES_SF_FLAT_H_
