// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_TELEMETRY_SF_FLAT_TELEMETRY_H_
#define FLATBUFFERS_GENERATED_TELEMETRY_SF_FLAT_TELEMETRY_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

#include "SFTypes_generated.h"

namespace SF {
namespace Flat {
namespace Telemetry {

struct TelemetryPacket;
struct TelemetryPacketBuilder;

struct EventAttributeString;
struct EventAttributeStringBuilder;

struct EventAttributeInt;
struct EventAttributeIntBuilder;

struct EventAttributeUInt;
struct EventAttributeUIntBuilder;

struct EventAttributeInt64;
struct EventAttributeInt64Builder;

struct EventAttributeUInt64;
struct EventAttributeUInt64Builder;

struct EventAttributeFloat;
struct EventAttributeFloatBuilder;

struct EventAttributeDouble;
struct EventAttributeDoubleBuilder;

struct EventAttributeBool;
struct EventAttributeBoolBuilder;

struct EventAttribute;
struct EventAttributeBuilder;

struct PostEventRequest;
struct PostEventRequestBuilder;

struct PostEventResult;
struct PostEventResultBuilder;

enum PayloadData : uint8_t {
  PayloadData_NONE = 0,
  PayloadData_GenericError = 1,
  PayloadData_PostEventRequest = 2,
  PayloadData_PostEventResult = 3,
  PayloadData_MIN = PayloadData_NONE,
  PayloadData_MAX = PayloadData_PostEventResult
};

inline const PayloadData (&EnumValuesPayloadData())[4] {
  static const PayloadData values[] = {
    PayloadData_NONE,
    PayloadData_GenericError,
    PayloadData_PostEventRequest,
    PayloadData_PostEventResult
  };
  return values;
}

inline const char * const *EnumNamesPayloadData() {
  static const char * const names[5] = {
    "NONE",
    "GenericError",
    "PostEventRequest",
    "PostEventResult",
    nullptr
  };
  return names;
}

inline const char *EnumNamePayloadData(PayloadData e) {
  if (::flatbuffers::IsOutRange(e, PayloadData_NONE, PayloadData_PostEventResult)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPayloadData()[index];
}

template<typename T> struct PayloadDataTraits {
  static const PayloadData enum_value = PayloadData_NONE;
};

template<> struct PayloadDataTraits<SF::Flat::GenericError> {
  static const PayloadData enum_value = PayloadData_GenericError;
};

template<> struct PayloadDataTraits<SF::Flat::Telemetry::PostEventRequest> {
  static const PayloadData enum_value = PayloadData_PostEventRequest;
};

template<> struct PayloadDataTraits<SF::Flat::Telemetry::PostEventResult> {
  static const PayloadData enum_value = PayloadData_PostEventResult;
};

bool VerifyPayloadData(::flatbuffers::Verifier &verifier, const void *obj, PayloadData type);
bool VerifyPayloadDataVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

enum EventAttributeValue : uint8_t {
  EventAttributeValue_NONE = 0,
  EventAttributeValue_EventAttributeString = 1,
  EventAttributeValue_EventAttributeBool = 2,
  EventAttributeValue_EventAttributeFloat = 3,
  EventAttributeValue_EventAttributeDouble = 4,
  EventAttributeValue_EventAttributeInt = 5,
  EventAttributeValue_EventAttributeUInt = 6,
  EventAttributeValue_EventAttributeInt64 = 7,
  EventAttributeValue_EventAttributeUInt64 = 8,
  EventAttributeValue_MIN = EventAttributeValue_NONE,
  EventAttributeValue_MAX = EventAttributeValue_EventAttributeUInt64
};

inline const EventAttributeValue (&EnumValuesEventAttributeValue())[9] {
  static const EventAttributeValue values[] = {
    EventAttributeValue_NONE,
    EventAttributeValue_EventAttributeString,
    EventAttributeValue_EventAttributeBool,
    EventAttributeValue_EventAttributeFloat,
    EventAttributeValue_EventAttributeDouble,
    EventAttributeValue_EventAttributeInt,
    EventAttributeValue_EventAttributeUInt,
    EventAttributeValue_EventAttributeInt64,
    EventAttributeValue_EventAttributeUInt64
  };
  return values;
}

inline const char * const *EnumNamesEventAttributeValue() {
  static const char * const names[10] = {
    "NONE",
    "EventAttributeString",
    "EventAttributeBool",
    "EventAttributeFloat",
    "EventAttributeDouble",
    "EventAttributeInt",
    "EventAttributeUInt",
    "EventAttributeInt64",
    "EventAttributeUInt64",
    nullptr
  };
  return names;
}

inline const char *EnumNameEventAttributeValue(EventAttributeValue e) {
  if (::flatbuffers::IsOutRange(e, EventAttributeValue_NONE, EventAttributeValue_EventAttributeUInt64)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesEventAttributeValue()[index];
}

template<typename T> struct EventAttributeValueTraits {
  static const EventAttributeValue enum_value = EventAttributeValue_NONE;
};

template<> struct EventAttributeValueTraits<SF::Flat::Telemetry::EventAttributeString> {
  static const EventAttributeValue enum_value = EventAttributeValue_EventAttributeString;
};

template<> struct EventAttributeValueTraits<SF::Flat::Telemetry::EventAttributeBool> {
  static const EventAttributeValue enum_value = EventAttributeValue_EventAttributeBool;
};

template<> struct EventAttributeValueTraits<SF::Flat::Telemetry::EventAttributeFloat> {
  static const EventAttributeValue enum_value = EventAttributeValue_EventAttributeFloat;
};

template<> struct EventAttributeValueTraits<SF::Flat::Telemetry::EventAttributeDouble> {
  static const EventAttributeValue enum_value = EventAttributeValue_EventAttributeDouble;
};

template<> struct EventAttributeValueTraits<SF::Flat::Telemetry::EventAttributeInt> {
  static const EventAttributeValue enum_value = EventAttributeValue_EventAttributeInt;
};

template<> struct EventAttributeValueTraits<SF::Flat::Telemetry::EventAttributeUInt> {
  static const EventAttributeValue enum_value = EventAttributeValue_EventAttributeUInt;
};

template<> struct EventAttributeValueTraits<SF::Flat::Telemetry::EventAttributeInt64> {
  static const EventAttributeValue enum_value = EventAttributeValue_EventAttributeInt64;
};

template<> struct EventAttributeValueTraits<SF::Flat::Telemetry::EventAttributeUInt64> {
  static const EventAttributeValue enum_value = EventAttributeValue_EventAttributeUInt64;
};

bool VerifyEventAttributeValue(::flatbuffers::Verifier &verifier, const void *obj, EventAttributeValue type);
bool VerifyEventAttributeValueVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct TelemetryPacket FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TelemetryPacketBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PAYLOAD_DATA_TYPE = 4,
    VT_PAYLOAD_DATA = 6
  };
  SF::Flat::Telemetry::PayloadData payload_data_type() const {
    return static_cast<SF::Flat::Telemetry::PayloadData>(GetField<uint8_t>(VT_PAYLOAD_DATA_TYPE, 0));
  }
  const void *payload_data() const {
    return GetPointer<const void *>(VT_PAYLOAD_DATA);
  }
  template<typename T> const T *payload_data_as() const;
  const SF::Flat::GenericError *payload_data_as_GenericError() const {
    return payload_data_type() == SF::Flat::Telemetry::PayloadData_GenericError ? static_cast<const SF::Flat::GenericError *>(payload_data()) : nullptr;
  }
  const SF::Flat::Telemetry::PostEventRequest *payload_data_as_PostEventRequest() const {
    return payload_data_type() == SF::Flat::Telemetry::PayloadData_PostEventRequest ? static_cast<const SF::Flat::Telemetry::PostEventRequest *>(payload_data()) : nullptr;
  }
  const SF::Flat::Telemetry::PostEventResult *payload_data_as_PostEventResult() const {
    return payload_data_type() == SF::Flat::Telemetry::PayloadData_PostEventResult ? static_cast<const SF::Flat::Telemetry::PostEventResult *>(payload_data()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_PAYLOAD_DATA_TYPE, 1) &&
           VerifyOffset(verifier, VT_PAYLOAD_DATA) &&
           VerifyPayloadData(verifier, payload_data(), payload_data_type()) &&
           verifier.EndTable();
  }
};

template<> inline const SF::Flat::GenericError *TelemetryPacket::payload_data_as<SF::Flat::GenericError>() const {
  return payload_data_as_GenericError();
}

template<> inline const SF::Flat::Telemetry::PostEventRequest *TelemetryPacket::payload_data_as<SF::Flat::Telemetry::PostEventRequest>() const {
  return payload_data_as_PostEventRequest();
}

template<> inline const SF::Flat::Telemetry::PostEventResult *TelemetryPacket::payload_data_as<SF::Flat::Telemetry::PostEventResult>() const {
  return payload_data_as_PostEventResult();
}

struct TelemetryPacketBuilder {
  typedef TelemetryPacket Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_payload_data_type(SF::Flat::Telemetry::PayloadData payload_data_type) {
    fbb_.AddElement<uint8_t>(TelemetryPacket::VT_PAYLOAD_DATA_TYPE, static_cast<uint8_t>(payload_data_type), 0);
  }
  void add_payload_data(::flatbuffers::Offset<void> payload_data) {
    fbb_.AddOffset(TelemetryPacket::VT_PAYLOAD_DATA, payload_data);
  }
  explicit TelemetryPacketBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TelemetryPacket> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TelemetryPacket>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<TelemetryPacket> CreateTelemetryPacket(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    SF::Flat::Telemetry::PayloadData payload_data_type = SF::Flat::Telemetry::PayloadData_NONE,
    ::flatbuffers::Offset<void> payload_data = 0) {
  TelemetryPacketBuilder builder_(_fbb);
  builder_.add_payload_data(payload_data);
  builder_.add_payload_data_type(payload_data_type);
  return builder_.Finish();
}

struct EventAttributeString FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EventAttributeStringBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUE = 4
  };
  const ::flatbuffers::String *value() const {
    return GetPointer<const ::flatbuffers::String *>(VT_VALUE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_VALUE) &&
           verifier.VerifyString(value()) &&
           verifier.EndTable();
  }
};

struct EventAttributeStringBuilder {
  typedef EventAttributeString Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_value(::flatbuffers::Offset<::flatbuffers::String> value) {
    fbb_.AddOffset(EventAttributeString::VT_VALUE, value);
  }
  explicit EventAttributeStringBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EventAttributeString> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EventAttributeString>(end);
    fbb_.Required(o, EventAttributeString::VT_VALUE);
    return o;
  }
};

inline ::flatbuffers::Offset<EventAttributeString> CreateEventAttributeString(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> value = 0) {
  EventAttributeStringBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<EventAttributeString> CreateEventAttributeStringDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *value = nullptr) {
  auto value__ = value ? _fbb.CreateString(value) : 0;
  return SF::Flat::Telemetry::CreateEventAttributeString(
      _fbb,
      value__);
}

struct EventAttributeInt FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EventAttributeIntBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUE = 4
  };
  int32_t value() const {
    return GetField<int32_t>(VT_VALUE, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_VALUE, 4) &&
           verifier.EndTable();
  }
};

struct EventAttributeIntBuilder {
  typedef EventAttributeInt Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_value(int32_t value) {
    fbb_.AddElement<int32_t>(EventAttributeInt::VT_VALUE, value, 0);
  }
  explicit EventAttributeIntBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EventAttributeInt> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EventAttributeInt>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<EventAttributeInt> CreateEventAttributeInt(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t value = 0) {
  EventAttributeIntBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

struct EventAttributeUInt FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EventAttributeUIntBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUE = 4
  };
  uint32_t value() const {
    return GetField<uint32_t>(VT_VALUE, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_VALUE, 4) &&
           verifier.EndTable();
  }
};

struct EventAttributeUIntBuilder {
  typedef EventAttributeUInt Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_value(uint32_t value) {
    fbb_.AddElement<uint32_t>(EventAttributeUInt::VT_VALUE, value, 0);
  }
  explicit EventAttributeUIntBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EventAttributeUInt> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EventAttributeUInt>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<EventAttributeUInt> CreateEventAttributeUInt(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t value = 0) {
  EventAttributeUIntBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

struct EventAttributeInt64 FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EventAttributeInt64Builder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUE = 4
  };
  int64_t value() const {
    return GetField<int64_t>(VT_VALUE, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_VALUE, 8) &&
           verifier.EndTable();
  }
};

struct EventAttributeInt64Builder {
  typedef EventAttributeInt64 Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_value(int64_t value) {
    fbb_.AddElement<int64_t>(EventAttributeInt64::VT_VALUE, value, 0);
  }
  explicit EventAttributeInt64Builder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EventAttributeInt64> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EventAttributeInt64>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<EventAttributeInt64> CreateEventAttributeInt64(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int64_t value = 0) {
  EventAttributeInt64Builder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

struct EventAttributeUInt64 FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EventAttributeUInt64Builder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUE = 4
  };
  uint64_t value() const {
    return GetField<uint64_t>(VT_VALUE, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_VALUE, 8) &&
           verifier.EndTable();
  }
};

struct EventAttributeUInt64Builder {
  typedef EventAttributeUInt64 Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_value(uint64_t value) {
    fbb_.AddElement<uint64_t>(EventAttributeUInt64::VT_VALUE, value, 0);
  }
  explicit EventAttributeUInt64Builder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EventAttributeUInt64> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EventAttributeUInt64>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<EventAttributeUInt64> CreateEventAttributeUInt64(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t value = 0) {
  EventAttributeUInt64Builder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

struct EventAttributeFloat FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EventAttributeFloatBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUE = 4
  };
  float value() const {
    return GetField<float>(VT_VALUE, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_VALUE, 4) &&
           verifier.EndTable();
  }
};

struct EventAttributeFloatBuilder {
  typedef EventAttributeFloat Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_value(float value) {
    fbb_.AddElement<float>(EventAttributeFloat::VT_VALUE, value, 0.0f);
  }
  explicit EventAttributeFloatBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EventAttributeFloat> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EventAttributeFloat>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<EventAttributeFloat> CreateEventAttributeFloat(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float value = 0.0f) {
  EventAttributeFloatBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

struct EventAttributeDouble FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EventAttributeDoubleBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUE = 4
  };
  double value() const {
    return GetField<double>(VT_VALUE, 0.0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_VALUE, 8) &&
           verifier.EndTable();
  }
};

struct EventAttributeDoubleBuilder {
  typedef EventAttributeDouble Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_value(double value) {
    fbb_.AddElement<double>(EventAttributeDouble::VT_VALUE, value, 0.0);
  }
  explicit EventAttributeDoubleBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EventAttributeDouble> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EventAttributeDouble>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<EventAttributeDouble> CreateEventAttributeDouble(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double value = 0.0) {
  EventAttributeDoubleBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

struct EventAttributeBool FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EventAttributeBoolBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUE = 4
  };
  bool value() const {
    return GetField<uint8_t>(VT_VALUE, 0) != 0;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_VALUE, 1) &&
           verifier.EndTable();
  }
};

struct EventAttributeBoolBuilder {
  typedef EventAttributeBool Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_value(bool value) {
    fbb_.AddElement<uint8_t>(EventAttributeBool::VT_VALUE, static_cast<uint8_t>(value), 0);
  }
  explicit EventAttributeBoolBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EventAttributeBool> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EventAttributeBool>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<EventAttributeBool> CreateEventAttributeBool(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool value = false) {
  EventAttributeBoolBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

struct EventAttribute FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EventAttributeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_VALUE_TYPE = 6,
    VT_VALUE = 8
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  SF::Flat::Telemetry::EventAttributeValue value_type() const {
    return static_cast<SF::Flat::Telemetry::EventAttributeValue>(GetField<uint8_t>(VT_VALUE_TYPE, 0));
  }
  const void *value() const {
    return GetPointer<const void *>(VT_VALUE);
  }
  template<typename T> const T *value_as() const;
  const SF::Flat::Telemetry::EventAttributeString *value_as_EventAttributeString() const {
    return value_type() == SF::Flat::Telemetry::EventAttributeValue_EventAttributeString ? static_cast<const SF::Flat::Telemetry::EventAttributeString *>(value()) : nullptr;
  }
  const SF::Flat::Telemetry::EventAttributeBool *value_as_EventAttributeBool() const {
    return value_type() == SF::Flat::Telemetry::EventAttributeValue_EventAttributeBool ? static_cast<const SF::Flat::Telemetry::EventAttributeBool *>(value()) : nullptr;
  }
  const SF::Flat::Telemetry::EventAttributeFloat *value_as_EventAttributeFloat() const {
    return value_type() == SF::Flat::Telemetry::EventAttributeValue_EventAttributeFloat ? static_cast<const SF::Flat::Telemetry::EventAttributeFloat *>(value()) : nullptr;
  }
  const SF::Flat::Telemetry::EventAttributeDouble *value_as_EventAttributeDouble() const {
    return value_type() == SF::Flat::Telemetry::EventAttributeValue_EventAttributeDouble ? static_cast<const SF::Flat::Telemetry::EventAttributeDouble *>(value()) : nullptr;
  }
  const SF::Flat::Telemetry::EventAttributeInt *value_as_EventAttributeInt() const {
    return value_type() == SF::Flat::Telemetry::EventAttributeValue_EventAttributeInt ? static_cast<const SF::Flat::Telemetry::EventAttributeInt *>(value()) : nullptr;
  }
  const SF::Flat::Telemetry::EventAttributeUInt *value_as_EventAttributeUInt() const {
    return value_type() == SF::Flat::Telemetry::EventAttributeValue_EventAttributeUInt ? static_cast<const SF::Flat::Telemetry::EventAttributeUInt *>(value()) : nullptr;
  }
  const SF::Flat::Telemetry::EventAttributeInt64 *value_as_EventAttributeInt64() const {
    return value_type() == SF::Flat::Telemetry::EventAttributeValue_EventAttributeInt64 ? static_cast<const SF::Flat::Telemetry::EventAttributeInt64 *>(value()) : nullptr;
  }
  const SF::Flat::Telemetry::EventAttributeUInt64 *value_as_EventAttributeUInt64() const {
    return value_type() == SF::Flat::Telemetry::EventAttributeValue_EventAttributeUInt64 ? static_cast<const SF::Flat::Telemetry::EventAttributeUInt64 *>(value()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<uint8_t>(verifier, VT_VALUE_TYPE, 1) &&
           VerifyOffsetRequired(verifier, VT_VALUE) &&
           VerifyEventAttributeValue(verifier, value(), value_type()) &&
           verifier.EndTable();
  }
};

template<> inline const SF::Flat::Telemetry::EventAttributeString *EventAttribute::value_as<SF::Flat::Telemetry::EventAttributeString>() const {
  return value_as_EventAttributeString();
}

template<> inline const SF::Flat::Telemetry::EventAttributeBool *EventAttribute::value_as<SF::Flat::Telemetry::EventAttributeBool>() const {
  return value_as_EventAttributeBool();
}

template<> inline const SF::Flat::Telemetry::EventAttributeFloat *EventAttribute::value_as<SF::Flat::Telemetry::EventAttributeFloat>() const {
  return value_as_EventAttributeFloat();
}

template<> inline const SF::Flat::Telemetry::EventAttributeDouble *EventAttribute::value_as<SF::Flat::Telemetry::EventAttributeDouble>() const {
  return value_as_EventAttributeDouble();
}

template<> inline const SF::Flat::Telemetry::EventAttributeInt *EventAttribute::value_as<SF::Flat::Telemetry::EventAttributeInt>() const {
  return value_as_EventAttributeInt();
}

template<> inline const SF::Flat::Telemetry::EventAttributeUInt *EventAttribute::value_as<SF::Flat::Telemetry::EventAttributeUInt>() const {
  return value_as_EventAttributeUInt();
}

template<> inline const SF::Flat::Telemetry::EventAttributeInt64 *EventAttribute::value_as<SF::Flat::Telemetry::EventAttributeInt64>() const {
  return value_as_EventAttributeInt64();
}

template<> inline const SF::Flat::Telemetry::EventAttributeUInt64 *EventAttribute::value_as<SF::Flat::Telemetry::EventAttributeUInt64>() const {
  return value_as_EventAttributeUInt64();
}

struct EventAttributeBuilder {
  typedef EventAttribute Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(EventAttribute::VT_NAME, name);
  }
  void add_value_type(SF::Flat::Telemetry::EventAttributeValue value_type) {
    fbb_.AddElement<uint8_t>(EventAttribute::VT_VALUE_TYPE, static_cast<uint8_t>(value_type), 0);
  }
  void add_value(::flatbuffers::Offset<void> value) {
    fbb_.AddOffset(EventAttribute::VT_VALUE, value);
  }
  explicit EventAttributeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EventAttribute> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EventAttribute>(end);
    fbb_.Required(o, EventAttribute::VT_NAME);
    fbb_.Required(o, EventAttribute::VT_VALUE);
    return o;
  }
};

inline ::flatbuffers::Offset<EventAttribute> CreateEventAttribute(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    SF::Flat::Telemetry::EventAttributeValue value_type = SF::Flat::Telemetry::EventAttributeValue_NONE,
    ::flatbuffers::Offset<void> value = 0) {
  EventAttributeBuilder builder_(_fbb);
  builder_.add_value(value);
  builder_.add_name(name);
  builder_.add_value_type(value_type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<EventAttribute> CreateEventAttributeDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    SF::Flat::Telemetry::EventAttributeValue value_type = SF::Flat::Telemetry::EventAttributeValue_NONE,
    ::flatbuffers::Offset<void> value = 0) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return SF::Flat::Telemetry::CreateEventAttribute(
      _fbb,
      name__,
      value_type,
      value);
}

struct PostEventRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PostEventRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_EVENT_NAME = 4,
    VT_TIME_STAMP = 6,
    VT_APP_ID = 8,
    VT_MACHINE_ID = 10,
    VT_EVENT_ID = 12,
    VT_ACCOUNT_ID = 14,
    VT_IS_PLAY_EVENT = 16,
    VT_SESSION_ID = 18,
    VT_ATTRIBUTES = 20
  };
  const ::flatbuffers::String *event_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_EVENT_NAME);
  }
  uint64_t time_stamp() const {
    return GetField<uint64_t>(VT_TIME_STAMP, 0);
  }
  const ::flatbuffers::String *app_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_APP_ID);
  }
  const ::flatbuffers::String *machine_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MACHINE_ID);
  }
  uint32_t event_id() const {
    return GetField<uint32_t>(VT_EVENT_ID, 0);
  }
  uint64_t account_id() const {
    return GetField<uint64_t>(VT_ACCOUNT_ID, 0);
  }
  bool is_play_event() const {
    return GetField<uint8_t>(VT_IS_PLAY_EVENT, 0) != 0;
  }
  const ::flatbuffers::Vector<uint8_t> *session_id() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_SESSION_ID);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<SF::Flat::Telemetry::EventAttribute>> *attributes() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<SF::Flat::Telemetry::EventAttribute>> *>(VT_ATTRIBUTES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_EVENT_NAME) &&
           verifier.VerifyString(event_name()) &&
           VerifyField<uint64_t>(verifier, VT_TIME_STAMP, 8) &&
           VerifyOffset(verifier, VT_APP_ID) &&
           verifier.VerifyString(app_id()) &&
           VerifyOffset(verifier, VT_MACHINE_ID) &&
           verifier.VerifyString(machine_id()) &&
           VerifyField<uint32_t>(verifier, VT_EVENT_ID, 4) &&
           VerifyField<uint64_t>(verifier, VT_ACCOUNT_ID, 8) &&
           VerifyField<uint8_t>(verifier, VT_IS_PLAY_EVENT, 1) &&
           VerifyOffsetRequired(verifier, VT_SESSION_ID) &&
           verifier.VerifyVector(session_id()) &&
           VerifyOffset(verifier, VT_ATTRIBUTES) &&
           verifier.VerifyVector(attributes()) &&
           verifier.VerifyVectorOfTables(attributes()) &&
           verifier.EndTable();
  }
};

struct PostEventRequestBuilder {
  typedef PostEventRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_event_name(::flatbuffers::Offset<::flatbuffers::String> event_name) {
    fbb_.AddOffset(PostEventRequest::VT_EVENT_NAME, event_name);
  }
  void add_time_stamp(uint64_t time_stamp) {
    fbb_.AddElement<uint64_t>(PostEventRequest::VT_TIME_STAMP, time_stamp, 0);
  }
  void add_app_id(::flatbuffers::Offset<::flatbuffers::String> app_id) {
    fbb_.AddOffset(PostEventRequest::VT_APP_ID, app_id);
  }
  void add_machine_id(::flatbuffers::Offset<::flatbuffers::String> machine_id) {
    fbb_.AddOffset(PostEventRequest::VT_MACHINE_ID, machine_id);
  }
  void add_event_id(uint32_t event_id) {
    fbb_.AddElement<uint32_t>(PostEventRequest::VT_EVENT_ID, event_id, 0);
  }
  void add_account_id(uint64_t account_id) {
    fbb_.AddElement<uint64_t>(PostEventRequest::VT_ACCOUNT_ID, account_id, 0);
  }
  void add_is_play_event(bool is_play_event) {
    fbb_.AddElement<uint8_t>(PostEventRequest::VT_IS_PLAY_EVENT, static_cast<uint8_t>(is_play_event), 0);
  }
  void add_session_id(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> session_id) {
    fbb_.AddOffset(PostEventRequest::VT_SESSION_ID, session_id);
  }
  void add_attributes(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<SF::Flat::Telemetry::EventAttribute>>> attributes) {
    fbb_.AddOffset(PostEventRequest::VT_ATTRIBUTES, attributes);
  }
  explicit PostEventRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PostEventRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PostEventRequest>(end);
    fbb_.Required(o, PostEventRequest::VT_EVENT_NAME);
    fbb_.Required(o, PostEventRequest::VT_SESSION_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<PostEventRequest> CreatePostEventRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> event_name = 0,
    uint64_t time_stamp = 0,
    ::flatbuffers::Offset<::flatbuffers::String> app_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> machine_id = 0,
    uint32_t event_id = 0,
    uint64_t account_id = 0,
    bool is_play_event = false,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> session_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<SF::Flat::Telemetry::EventAttribute>>> attributes = 0) {
  PostEventRequestBuilder builder_(_fbb);
  builder_.add_account_id(account_id);
  builder_.add_time_stamp(time_stamp);
  builder_.add_attributes(attributes);
  builder_.add_session_id(session_id);
  builder_.add_event_id(event_id);
  builder_.add_machine_id(machine_id);
  builder_.add_app_id(app_id);
  builder_.add_event_name(event_name);
  builder_.add_is_play_event(is_play_event);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<PostEventRequest> CreatePostEventRequestDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *event_name = nullptr,
    uint64_t time_stamp = 0,
    const char *app_id = nullptr,
    const char *machine_id = nullptr,
    uint32_t event_id = 0,
    uint64_t account_id = 0,
    bool is_play_event = false,
    const std::vector<uint8_t> *session_id = nullptr,
    const std::vector<::flatbuffers::Offset<SF::Flat::Telemetry::EventAttribute>> *attributes = nullptr) {
  auto event_name__ = event_name ? _fbb.CreateString(event_name) : 0;
  auto app_id__ = app_id ? _fbb.CreateString(app_id) : 0;
  auto machine_id__ = machine_id ? _fbb.CreateString(machine_id) : 0;
  auto session_id__ = session_id ? _fbb.CreateVector<uint8_t>(*session_id) : 0;
  auto attributes__ = attributes ? _fbb.CreateVector<::flatbuffers::Offset<SF::Flat::Telemetry::EventAttribute>>(*attributes) : 0;
  return SF::Flat::Telemetry::CreatePostEventRequest(
      _fbb,
      event_name__,
      time_stamp,
      app_id__,
      machine_id__,
      event_id,
      account_id,
      is_play_event,
      session_id__,
      attributes__);
}

struct PostEventResult FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PostEventResultBuilder Builder;
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct PostEventResultBuilder {
  typedef PostEventResult Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit PostEventResultBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PostEventResult> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PostEventResult>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PostEventResult> CreatePostEventResult(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  PostEventResultBuilder builder_(_fbb);
  return builder_.Finish();
}

inline bool VerifyPayloadData(::flatbuffers::Verifier &verifier, const void *obj, PayloadData type) {
  switch (type) {
    case PayloadData_NONE: {
      return true;
    }
    case PayloadData_GenericError: {
      auto ptr = reinterpret_cast<const SF::Flat::GenericError *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PayloadData_PostEventRequest: {
      auto ptr = reinterpret_cast<const SF::Flat::Telemetry::PostEventRequest *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PayloadData_PostEventResult: {
      auto ptr = reinterpret_cast<const SF::Flat::Telemetry::PostEventResult *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyPayloadDataVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyPayloadData(
        verifier,  values->Get(i), types->GetEnum<PayloadData>(i))) {
      return false;
    }
  }
  return true;
}

inline bool VerifyEventAttributeValue(::flatbuffers::Verifier &verifier, const void *obj, EventAttributeValue type) {
  switch (type) {
    case EventAttributeValue_NONE: {
      return true;
    }
    case EventAttributeValue_EventAttributeString: {
      auto ptr = reinterpret_cast<const SF::Flat::Telemetry::EventAttributeString *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case EventAttributeValue_EventAttributeBool: {
      auto ptr = reinterpret_cast<const SF::Flat::Telemetry::EventAttributeBool *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case EventAttributeValue_EventAttributeFloat: {
      auto ptr = reinterpret_cast<const SF::Flat::Telemetry::EventAttributeFloat *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case EventAttributeValue_EventAttributeDouble: {
      auto ptr = reinterpret_cast<const SF::Flat::Telemetry::EventAttributeDouble *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case EventAttributeValue_EventAttributeInt: {
      auto ptr = reinterpret_cast<const SF::Flat::Telemetry::EventAttributeInt *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case EventAttributeValue_EventAttributeUInt: {
      auto ptr = reinterpret_cast<const SF::Flat::Telemetry::EventAttributeUInt *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case EventAttributeValue_EventAttributeInt64: {
      auto ptr = reinterpret_cast<const SF::Flat::Telemetry::EventAttributeInt64 *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case EventAttributeValue_EventAttributeUInt64: {
      auto ptr = reinterpret_cast<const SF::Flat::Telemetry::EventAttributeUInt64 *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyEventAttributeValueVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyEventAttributeValue(
        verifier,  values->Get(i), types->GetEnum<EventAttributeValue>(i))) {
      return false;
    }
  }
  return true;
}

inline const SF::Flat::Telemetry::TelemetryPacket *GetTelemetryPacket(const void *buf) {
  return ::flatbuffers::GetRoot<SF::Flat::Telemetry::TelemetryPacket>(buf);
}

inline const SF::Flat::Telemetry::TelemetryPacket *GetSizePrefixedTelemetryPacket(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<SF::Flat::Telemetry::TelemetryPacket>(buf);
}

inline bool VerifyTelemetryPacketBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<SF::Flat::Telemetry::TelemetryPacket>(nullptr);
}

inline bool VerifySizePrefixedTelemetryPacketBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<SF::Flat::Telemetry::TelemetryPacket>(nullptr);
}

inline void FinishTelemetryPacketBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SF::Flat::Telemetry::TelemetryPacket> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedTelemetryPacketBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SF::Flat::Telemetry::TelemetryPacket> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Telemetry
}  // namespace Flat
}  // namespace SF

#endif  // FLATBUFFERS_GENERATED_TELEMETRY_SF_FLAT_TELEMETRY_H_
