

export CMAKE_SYSTEM_NAME=Linux
export PROCESS_ARCHITECTUR=x64
export AVRO_PATH=../../../src/avro/avro-src-1.10.2
export INTERMEDIATE_DIR=../../$CMAKE_SYSTEM_NAME/avro


if [ ! -d "$INTERMEDIATE_DIR" ]; then
	mkdir $INTERMEDIATE_DIR
fi

if [ ! -d "$INTERMEDIATE_DIR/Debug" ]; then
	mkdir $INTERMEDIATE_DIR/Debug
fi

if [ ! -d "$INTERMEDIATE_DIR/RelWithDebInfo" ]; then
	mkdir $INTERMEDIATE_DIR/RelWithDebInfo
fi


pushd $INTERMEDIATE_DIR



export CONFIGURATION=Debug
pushd $CONFIGURATION
cmake $AVRO_PATH/lang/c -G "Ninja" -DCMAKE_BUILD_TYPE=$CONFIGURATION  \
	-DCMAKE_INSTALL_PREFIX=../../$CONFIGURATION  -DCMAKE_SYSTEM_NAME=$CMAKE_SYSTEM_NAME \
	-DZLIB_ROOT=../../$CONFIGURATION/ -DZLIB_LIBRARY=zlib \
	-DCMAKE_APPBUNDLE_PATH=../../$CONFIGURATION; \

popd


export CONFIGURATION=RelWithDebInfo
pushd $CONFIGURATION
cmake $AVRO_PATH/lang/c -G "Ninja"  -DCMAKE_BUILD_TYPE=$CONFIGURATION \
	-DCMAKE_INSTALL_PREFIX=../../$CONFIGURATION  -DCMAKE_SYSTEM_NAME=$CMAKE_SYSTEM_NAME \
	-DZLIB_ROOT=../../$CONFIGURATION/ -DZLIB_LIBRARY=zlib \
	-DCMAKE_APPBUNDLE_PATH=../../$CONFIGURATION; \

popd
popd


export LD_LIBRARY_PATH=$SavedLinkDir

