


rem set PATH=C:\DevEnv\Android\cmake\3.10.2.4988404\bin;%PATH%
set CMAKE_SYSTEM_NAME=Android
set PROCESS_ARCHITECTUR=armeabi-v7a


if not exist %CMAKE_SYSTEM_NAME% mkdir %CMAKE_SYSTEM_NAME%
set BUILD_DIR=%CMAKE_SYSTEM_NAME%



if not exist %BUILD_DIR% mkdir %BUILD_DIR%
if not exist %BUILD_DIR%\%PROCESS_ARCHITECTUR%Debug mkdir %BUILD_DIR%\%PROCESS_ARCHITECTUR%Debug
if not exist %BUILD_DIR%\%PROCESS_ARCHITECTUR%Release mkdir %BUILD_DIR%\%PROCESS_ARCHITECTUR%Release



set CMAKE_BUILD_TYPE=Debug
cd %BUILD_DIR%\%PROCESS_ARCHITECTUR%%CMAKE_BUILD_TYPE%

cmake ../../ -G Ninja ^
	-DCMAKE_ANDROID_NDK=%ANDROID_NDK_ROOT% ^
	-DCMAKE_CROSSCOMPILING=true ^
	-DCMAKE_TOOLCHAIN_FILE=%ANDROID_NDK_ROOT%\build\cmake\android.toolchain.cmake ^
	-DANDROID_ABI=%PROCESS_ARCHITECTUR% ^
	-DANDROID_PLATFORM=android-23 ^
	-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=bin/lib/%CMAKE_SYSTEM_NAME% ^
	-DCMAKE_INSTALL_PREFIX=../../%CMAKE_SYSTEM_NAME%/%PROCESS_ARCHITECTUR%%CMAKE_BUILD_TYPE% ^
	-DCMAKE_BUILD_TYPE=%CMAKE_BUILD_TYPE% ^
	-DANDROID_NDK=%ANDROID_NDK_ROOT% ^
	-DCMAKE_ANDROID_ARCH_ABI=%PROCESS_ARCHITECTUR% ^
	-DCMAKE_TOOLCHAIN_FILE=%ANDROID_NDK_ROOT%\build\cmake\android.toolchain.cmake ^
	-DCMAKE_MAKE_PROGRAM=%ANDROID_HOME%\cmake\3.10.2.4988404\bin\ninja.exe ^
	-DCMAKE_EXPORT_COMPILE_COMMANDS=ON ^
	-DANDROID=1


set CMAKE_BUILD_TYPE=Release
cd ../%PROCESS_ARCHITECTUR%%CMAKE_BUILD_TYPE%

cmake ../../ -G Ninja ^
	-DCMAKE_ANDROID_NDK=%ANDROID_NDK_ROOT% ^
	-DCMAKE_CROSSCOMPILING=true ^
	-DCMAKE_TOOLCHAIN_FILE=%ANDROID_NDK_ROOT%\build\cmake\android.toolchain.cmake ^
	-DANDROID_ABI=%PROCESS_ARCHITECTUR% ^
	-DANDROID_PLATFORM=android-23 ^
	-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=bin/lib/%CMAKE_SYSTEM_NAME% ^
	-DCMAKE_INSTALL_PREFIX=../../%CMAKE_SYSTEM_NAME%/%PROCESS_ARCHITECTUR%%CMAKE_BUILD_TYPE% ^
	-DCMAKE_BUILD_TYPE=%CMAKE_BUILD_TYPE% ^
	-DANDROID_NDK=%ANDROID_NDK_ROOT% ^
	-DCMAKE_ANDROID_ARCH_ABI=%PROCESS_ARCHITECTUR% ^
	-DCMAKE_TOOLCHAIN_FILE=%ANDROID_NDK_ROOT%\build\cmake\android.toolchain.cmake ^
	-DCMAKE_MAKE_PROGRAM=%ANDROID_HOME%\cmake\3.10.2.4988404\bin\ninja.exe ^
	-DCMAKE_EXPORT_COMPILE_COMMANDS=ON ^
	-DANDROID=1


pause
