
set CMAKE_SYSTEM_NAME=Windows
set PROCESS_ARCHITECTUR=x64

call FindVC.cmd

if not exist %CMAKE_SYSTEM_NAME% mkdir %CMAKE_SYSTEM_NAME%
if not exist %CMAKE_SYSTEM_NAME%\Debug mkdir %CMAKE_SYSTEM_NAME%\Debug
if not exist %CMAKE_SYSTEM_NAME%\Release mkdir %CMAKE_SYSTEM_NAME%\Release

rem for %%I in (.) do set SF_FOLDER=%%~nxI\..
set SF_FOLDER=%~dp0..

set BUILD_DIR=%CMAKE_SYSTEM_NAME%\


cd %BUILD_DIR%


set CONFIGURATION=Debug
cd %CONFIGURATION%
cmake ../../ -G %VCCMAKEGENERATOR% -A %PROCESS_ARCHITECTUR%  ^
	-DCMAKE_INSTALL_PREFIX=../../%CMAKE_SYSTEM_NAME%/%CONFIGURATION% ^
	-DSF_FOLDER=%SF_FOLDER% ^
	-DVCPKG_DIR=%SF_FOLDER%/vcpkg

cd ..

set CONFIGURATION=Release
cd %CONFIGURATION%
cmake ../../ -G %VCCMAKEGENERATOR% -A %PROCESS_ARCHITECTUR%  ^
	-DCMAKE_INSTALL_PREFIX=../../%CMAKE_SYSTEM_NAME%/%CONFIGURATION% ^
	-DSF_FOLDER=%SF_FOLDER% ^
	-DVCPKG_DIR=%SF_FOLDER%/vcpkg


cd %~dp0

if not "%1" == "nopause" pause

