// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SF.Flat.Telemetry
{

public enum EventAttributeValue : byte
{
  NONE = 0,
  EventAttributeString = 1,
  EventAttributeBool = 2,
  EventAttributeFloat = 3,
  EventAttributeDouble = 4,
  EventAttributeInt = 5,
  EventAttributeUInt = 6,
  EventAttributeInt64 = 7,
  EventAttributeUInt64 = 8,
};


}
