// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SF.Flat.Telemetry
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct EventAttributeInt : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static EventAttributeInt GetRootAsEventAttributeInt(ByteBuffer _bb) { return GetRootAsEventAttributeInt(_bb, new EventAttributeInt()); }
  public static EventAttributeInt GetRootAsEventAttributeInt(ByteBuffer _bb, EventAttributeInt obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public EventAttributeInt __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Value { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<SF.Flat.Telemetry.EventAttributeInt> CreateEventAttributeInt(FlatBufferBuilder builder,
      int value = 0) {
    builder.StartTable(1);
    EventAttributeInt.AddValue(builder, value);
    return EventAttributeInt.EndEventAttributeInt(builder);
  }

  public static void StartEventAttributeInt(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddValue(FlatBufferBuilder builder, int value) { builder.AddInt(0, value, 0); }
  public static Offset<SF.Flat.Telemetry.EventAttributeInt> EndEventAttributeInt(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SF.Flat.Telemetry.EventAttributeInt>(o);
  }
}


static public class EventAttributeIntVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Value*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
