// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SF.Flat.Telemetry
{

public enum PayloadData : byte
{
  NONE = 0,
  GenericError = 1,
  PostEventRequest = 2,
  PostEventResult = 3,
};


}
