

set CMAKE_SYSTEM_NAME=Windows
set PROCESS_ARCHITECTUR=x64
set SRC_BASE=src
set SRC_PATH=../%SRC_BASE%
set INTERMEDIATE_DIR=TestBuild

rem if not exist %SRC_BASE%  call download.cmd

call ..\..\FindVC.cmd

if not exist %INTERMEDIATE_DIR% mkdir %INTERMEDIATE_DIR%

cd %INTERMEDIATE_DIR%

set CONFIGURATION=Debug

cmake %SRC_PATH% -G %VCCMAKEGENERATOR% -A %PROCESS_ARCHITECTUR%  ^
	-DCMAKE_INSTALL_PREFIX=../../../%CMAKE_SYSTEM_NAME%/%CONFIGURATION%  -DCMAKE_SYSTEM_NAME=%CMAKE_SYSTEM_NAME% ^
	-DLWS_WITH_MINIMAL_EXAMPLES=1 ^
	-DLWS_WITHOUT_EXTENSIONS=0 -DLWS_WITH_THREADPOOL=1 -DLWS_WITH_HTTP_STREAM_COMPRESSION=1 -DLWS_IPV6=1 -DLWS_WITH_SOCKS5=1 ^
	-DLWS_WITH_ZLIB=1 -DLWS_WITH_BUNDLED_ZLIB=0 -DLWS_WITH_LIBEVENT=1 -DLWS_WITH_SHARED=0 ^
	-DLWS_EXT_PTHREAD_INCLUDE_DIR=../../../%CMAKE_SYSTEM_NAME%/%CONFIGURATION%/include ^
	-DLWS_EXT_PTHREAD_LIBRARIES=../../../%CMAKE_SYSTEM_NAME%/%CONFIGURATION%/lib/SFWinport.lib ^
	-DLWS_WITH_HTTP2=1 -DLWS_OPENSSL_INCLUDE_DIRS=../../../%CMAKE_SYSTEM_NAME%/Common/include ^
	-DLWS_OPENSSL_LIBRARIES="../../../%CMAKE_SYSTEM_NAME%/Common/lib/libssl.lib;../../../%CMAKE_SYSTEM_NAME%/Common/lib/libcrypto.lib"


cd %~dp0

pause